# WordDatabase.gd
# 300종 전체 한글 단어 타워 데이터베이스 (1글자 기본, 2글자 상위, 3글자 신화)
extends Node

const WORD_DATABASE: Dictionary = {
	"검": {
		"word": "검",
		"name": "검 (도검/참격)",
		"category": "weapon",
		"cost": 1,
		"damage": 10,
		"desc": "적에게 10의 강력한 물리 베기 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"도": {
		"word": "도",
		"name": "도 (단도/연속베기)",
		"category": "weapon",
		"cost": 1,
		"damage": 8,
		"desc": "단도를 날렵하게 휘둘러 8 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/blade_도/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"창": {
		"word": "창",
		"name": "창 (장창/관통)",
		"category": "weapon",
		"cost": 1,
		"damage": 12,
		"desc": "장창을 내질러 12 피해와 함께 경로 상의 적을 관통합니다.",
		"icon": "res://assets/01_무기_공격/spear_창/spear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"활": {
		"word": "활",
		"name": "활 (장궁/저격)",
		"category": "weapon",
		"cost": 1,
		"damage": 9,
		"desc": "먼 거리의 적에게 9의 정확한 화살을 발사합니다.",
		"icon": "res://assets/01_무기_공격/bow_활/bow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"봉": {
		"word": "봉",
		"name": "봉 (장봉/광역)",
		"category": "weapon",
		"cost": 1,
		"damage": 8,
		"desc": "장봉을 크게 회전시켜 범위 내 적들에게 8 타격을 입힙니다.",
		"icon": "res://assets/01_무기_공격/staff_봉/staff_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"쇠": {
		"word": "쇠",
		"name": "쇠 (금속/강타)",
		"category": "weapon",
		"cost": 1,
		"damage": 11,
		"desc": "쇳덩이를 내리쳐 11 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/iron_쇠/iron_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"못": {
		"word": "못",
		"name": "못 (대못/출혈)",
		"category": "weapon",
		"cost": 1,
		"damage": 7,
		"desc": "날카로운 대못을 박아 7 피해 및 초당 3 출혈 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/spike_못/spike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"날": {
		"word": "날",
		"name": "날 (칼날/절단)",
		"category": "weapon",
		"cost": 1,
		"damage": 9,
		"desc": "예리한 칼날로 베어 9 피해 및 30% 취약 표식을 부여합니다.",
		"icon": "res://assets/01_무기_공격/blade_날/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"삭": {
		"word": "삭",
		"name": "삭 (삭풍/참격)",
		"category": "weapon",
		"cost": 1,
		"damage": 10,
		"desc": "매서운 삭풍을 휘둘러 10 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/wind_slash_삭/wind_slash_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"일": {
		"word": "일",
		"name": "일 (일격/강타)",
		"category": "weapon",
		"cost": 1,
		"damage": 15,
		"desc": "혼신의 일격을 날려 15의 치명적인 단일 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"곡": {
		"word": "곡",
		"name": "곡 (곡괭이/채굴)",
		"category": "weapon",
		"cost": 1,
		"damage": 9,
		"desc": "곡괭이로 적을 찍어 9 피해를 입히고 추가 골드를 획득합니다.",
		"icon": "res://assets/01_무기_공격/pickaxe_곡/pickaxe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"낫": {
		"word": "낫",
		"name": "낫 (사신의낫/베기)",
		"category": "weapon",
		"cost": 1,
		"damage": 13,
		"desc": "거대한 낫을 휘둘러 13 광역 베기 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/scythe_낫/scythe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"추": {
		"word": "추",
		"name": "추 (철퇴추/스턴)",
		"category": "weapon",
		"cost": 1,
		"damage": 11,
		"desc": "무거운 쇠추를 던져 11 피해 및 0.5초 경직을 줍니다.",
		"icon": "res://assets/01_무기_공격/flail_추/flail_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"골": {
		"word": "골",
		"name": "골 (메이스/분쇄)",
		"category": "weapon",
		"cost": 1,
		"damage": 12,
		"desc": "육중한 철퇴로 내리쳐 12 분쇄 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/mace_골/mace_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"극": {
		"word": "극",
		"name": "극 (삼지창/찌르기)",
		"category": "weapon",
		"cost": 1,
		"damage": 13,
		"desc": "세 갈래 창날로 13의 날카로운 찌르기 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/trident_극/trident_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"총": {
		"word": "총",
		"name": "총 (총탄/원거리)",
		"category": "weapon",
		"cost": 1,
		"damage": 11,
		"desc": "마력 총탄을 발사하여 11 원거리 저격 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/gun_총/gun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"포": {
		"word": "포",
		"name": "포 (대포/폭격)",
		"category": "weapon",
		"cost": 1,
		"damage": 16,
		"desc": "대포를 발사하여 착탄 지점에 16의 강력한 폭발 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"권": {
		"word": "권",
		"name": "권 (주먹/정권)",
		"category": "weapon",
		"cost": 1,
		"damage": 10,
		"desc": "묵직한 주먹 강타로 10 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/fist_권/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"갑": {
		"word": "갑",
		"name": "갑 (철갑/가시파편)",
		"category": "defense",
		"cost": 1,
		"damage": 15,
		"desc": "가시 철갑 파편을 사방으로 발사하여 15 관통 물리 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"방": {
		"word": "방",
		"name": "방 (방패/충격파)",
		"category": "defense",
		"cost": 1,
		"damage": 12,
		"desc": "접근하는 적들에게 12 방어 충격파를 발사하여 넉백시킵니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"문": {
		"word": "문",
		"name": "문 (관문/철문낙하)",
		"category": "defense",
		"cost": 1,
		"damage": 14,
		"desc": "적의 경로 위에 거대한 철문을 내리찍어 14 피해 및 1.5초 기절을 줍니다.",
		"icon": "res://assets/02_방어_장비/gate_문/gate_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성": {
		"word": "성",
		"name": "성 (성채/요새포)",
		"category": "defense",
		"cost": 1,
		"damage": 18,
		"desc": "요새의 육중한 성채 방어포를 발사하여 18의 광역 포격 피해를 줍니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"산": {
		"word": "산",
		"name": "산 (태산/낙석)",
		"category": "defense",
		"cost": 1,
		"damage": 18,
		"desc": "태산 같은 거대한 낙석을 떨어뜨려 18 광역 피해 및 넉백을 입힙니다.",
		"icon": "res://assets/02_방어_장비/mountain_산/mountain_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"막": {
		"word": "막",
		"name": "막 (결계/감속장막)",
		"category": "defense",
		"cost": 1,
		"damage": 12,
		"desc": "지나가는 적에게 12 장막 충격을 주며 이동속도를 50% 감속시킵니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"완": {
		"word": "완",
		"name": "완 (완벽/철퇴타격)",
		"category": "defense",
		"cost": 1,
		"damage": 16,
		"desc": "완벽한 타이밍의 묵직한 강타로 16 단일 물리 피해 및 0.8초 기절을 줍니다.",
		"icon": "res://assets/02_방어_장비/guard_완/guard_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"인": {
		"word": "인",
		"name": "인 (인내/강철탄)",
		"category": "defense",
		"cost": 1,
		"damage": 14,
		"desc": "강철 같은 단단한 탄환을 쏘아보내어 14 단일 관통 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/patience_인/patience_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"언": {
		"word": "언",
		"name": "언 (언약/신성광선)",
		"category": "defense",
		"cost": 1,
		"damage": 15,
		"desc": "신성의 언약 빛기둥을 내리꽂아 15 신성 광역 피해를 적들에게 가합니다.",
		"icon": "res://assets/02_방어_장비/pledge_언/pledge_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"위": {
		"word": "위",
		"name": "위 (위성/궤도레이저)",
		"category": "defense",
		"cost": 1,
		"damage": 13,
		"desc": "주변을 회전하는 궤도 레이저를 연사하여 13 지속 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/orbit_위/orbit_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"벽": {
		"word": "벽",
		"name": "벽 (돌벽/방벽)",
		"category": "defense",
		"cost": 1,
		"damage": 14,
		"desc": "단단한 돌벽을 세워 14 피해 및 적들을 1초간 정지시킵니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"방패": {
		"word": "방패",
		"name": "방패 (방어/공속오라)",
		"category": "defense",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 20의 방어 충격파를 발사하며 주변 모든 아군 타워 공격속도를 +30% 증폭시킵니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"불": {
		"word": "불",
		"name": "불 (화염/화구)",
		"category": "element",
		"cost": 1,
		"damage": 7,
		"desc": "적에게 7 피해를 주고 초당 3의 화상 피해를 남깁니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"물": {
		"word": "물",
		"name": "물 (수류/물줄기)",
		"category": "element",
		"cost": 1,
		"damage": 6,
		"desc": "차가운 물줄기를 발사하여 6 피해 및 적을 20% 둔화시킵니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빛": {
		"word": "빛",
		"name": "빛 (광휘/섬광)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"desc": "눈부신 섬광을 터뜨려 8 광역 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/light_빛/light_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"흙": {
		"word": "흙",
		"name": "흙 (대지/토석)",
		"category": "element",
		"cost": 1,
		"damage": 9,
		"desc": "단단한 흙덩이를 던져 9 피해 및 0.3초 경직을 가합니다.",
		"icon": "res://assets/03_원소_마법/earth_흙/earth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"풍": {
		"word": "풍",
		"name": "풍 (바람/돌풍)",
		"category": "element",
		"cost": 1,
		"damage": 7,
		"desc": "회전하는 돌풍을 발사하여 7 피해 및 적을 뒤로 밀어냅니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙": {
		"word": "빙",
		"name": "빙 (얼음/빙결)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"desc": "날카로운 얼음 조각을 쏘아 8 피해 및 40% 둔화를 겁니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"뇌": {
		"word": "뇌",
		"name": "뇌 (번개/감전)",
		"category": "element",
		"cost": 1,
		"damage": 11,
		"desc": "번갯불을 내리쳐 11 피해 및 2체의 적에게 연쇄 감전을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"독": {
		"word": "독",
		"name": "독 (맹독/부식)",
		"category": "element",
		"cost": 1,
		"damage": 6,
		"desc": "치명적인 독액을 뱉어 6 피해 및 초당 4의 지속 독 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/poison_독/poison_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"암": {
		"word": "암",
		"name": "암 (어둠/그림자)",
		"category": "element",
		"cost": 1,
		"damage": 10,
		"desc": "어둠의 파동을 뿜어내어 10 암흑 마법 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/dark_암/dark_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"염": {
		"word": "염",
		"name": "염 (화염/업화)",
		"category": "element",
		"cost": 1,
		"damage": 12,
		"desc": "작열하는 화염구를 투척하여 12 범위 화염 폭발을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/flame_염/flame_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"폭": {
		"word": "폭",
		"name": "폭 (폭발/화약)",
		"category": "element",
		"cost": 1,
		"damage": 15,
		"desc": "화약 폭탄을 터뜨려 반경 내 모든 적에게 15 폭발 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/explosion_폭/explosion_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"열": {
		"word": "열",
		"name": "열 (열기/화염)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"desc": "고열의 파동을 방출하여 8 지속 열기 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/heat_열/heat_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"냉": {
		"word": "냉",
		"name": "냉 (냉기/동결)",
		"category": "element",
		"cost": 1,
		"damage": 7,
		"desc": "서늘한 냉기를 뿜어 7 피해와 함께 적의 공속을 깎습니다.",
		"icon": "res://assets/03_원소_마법/cold_냉/cold_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"달": {
		"word": "달",
		"name": "달 (월광/마력)",
		"category": "element",
		"cost": 1,
		"damage": 10,
		"desc": "은은한 월광 마법탄을 발사하여 10 마법 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/moon_달/moon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"해": {
		"word": "해",
		"name": "해 (태양/광선)",
		"category": "element",
		"cost": 1,
		"damage": 13,
		"desc": "태양 광선을 집중 조사하여 13 지속 화염 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/sun_해/sun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"별": {
		"word": "별",
		"name": "별 (유성/낙하)",
		"category": "element",
		"cost": 1,
		"damage": 12,
		"desc": "작은 유성을 떨어뜨려 12 신성 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/star_별/star_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"새": {
		"word": "새",
		"name": "새 (조류/비행)",
		"category": "summon",
		"cost": 1,
		"damage": 7,
		"desc": "영리한 새를 날려 7의 빠른 쪼기 피해를 연속으로 가합니다.",
		"icon": "res://assets/04_생물_소환/bird_새/bird_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"뱀": {
		"word": "뱀",
		"name": "뱀 (파충/맹독)",
		"category": "summon",
		"cost": 1,
		"damage": 8,
		"desc": "독사를 소환하여 8 피해 및 초당 3의 중독 피해를 부여합니다.",
		"icon": "res://assets/04_생물_소환/snake_뱀/snake_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"곰": {
		"word": "곰",
		"name": "곰 (맹수/앞발)",
		"category": "summon",
		"cost": 1,
		"damage": 14,
		"desc": "거대한 곰의 앞발로 내리쳐 14 물리 피해 및 0.5초 기절을 가합니다.",
		"icon": "res://assets/04_생물_소환/bear_곰/bear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"벌": {
		"word": "벌",
		"name": "벌 (군집/독침)",
		"category": "summon",
		"cost": 1,
		"damage": 6,
		"desc": "사나운 벌떼를 날려 6 고속 다단히트 침 피해를 줍니다.",
		"icon": "res://assets/04_생물_소환/bee_벌/bee_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"쥐": {
		"word": "쥐",
		"name": "쥐 (역병/기습)",
		"category": "summon",
		"cost": 1,
		"damage": 6,
		"desc": "재빠른 역병 쥐를 풀어 6 피해 및 이동속도 20% 둔화를 겁니다.",
		"icon": "res://assets/04_생물_소환/rat_쥐/rat_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"소": {
		"word": "소",
		"name": "소 (황소/돌진)",
		"category": "summon",
		"cost": 1,
		"damage": 13,
		"desc": "성난 황소의 뿔로 들이받아 13 물리 피해 및 넉백을 가합니다.",
		"icon": "res://assets/04_생물_소환/bull_소/bull_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"말": {
		"word": "말",
		"name": "말 (군마/질주)",
		"category": "summon",
		"cost": 1,
		"damage": 11,
		"desc": "강력한 말발굽으로 짓밟아 11 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/horse_말/horse_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"개": {
		"word": "개",
		"name": "개 (사냥개/물어뜯기)",
		"category": "summon",
		"cost": 1,
		"damage": 9,
		"desc": "사냥개를 풀어 9 피해 및 1초간 적을 물고 늘어집니다.",
		"icon": "res://assets/04_생물_소환/dog_개/dog_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"호": {
		"word": "호",
		"name": "호 (호랑이/포효)",
		"category": "summon",
		"cost": 1,
		"damage": 16,
		"desc": "맹호의 포효를 내질러 16 강력 물리 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"용": {
		"word": "용",
		"name": "용 (드래곤/용염)",
		"category": "summon",
		"cost": 1,
		"damage": 18,
		"desc": "새끼 용을 소환하여 18의 맹렬한 브레스 화염을 뿜습니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"숨": {
		"word": "숨",
		"name": "숨 (숨결/영기방출)",
		"category": "heal",
		"cost": 1,
		"damage": 16,
		"desc": "전방 부채꼴 범위로 16의 거대한 영기 숨결을 뿜어냅니다.",
		"icon": "res://assets/05_회복_치유/breath_숨/breath_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"생": {
		"word": "생",
		"name": "생 (생명/영혼흡수)",
		"category": "heal",
		"cost": 1,
		"damage": 14,
		"desc": "적에게 14 영혼 흡수탄을 쏘며, 처치 시 기지 HP를 +1 회복합니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"샘": {
		"word": "샘",
		"name": "샘 (치유샘/물기둥)",
		"category": "heal",
		"cost": 1,
		"damage": 12,
		"desc": "바닥에서 솟구치는 거대한 물기둥으로 12 피해 및 0.5초 에어본을 가합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"감": {
		"word": "감",
		"name": "감 (단감/투척)",
		"category": "heal",
		"cost": 1,
		"damage": 11,
		"desc": "단단한 감 열매를 고속 투척하여 11 피해 및 30% 둔화를 줍니다.",
		"icon": "res://assets/05_회복_치유/persimmon_감/persimmon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"식": {
		"word": "식",
		"name": "식 (보양/독초폭탄)",
		"category": "heal",
		"cost": 1,
		"damage": 13,
		"desc": "폭발하는 독초 주머니를 던져 13 광역 피해 및 초당 4 중독 피해를 남깁니다.",
		"icon": "res://assets/05_회복_치유/food_식/food_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"무": {
		"word": "무",
		"name": "무 (무/대포탄)",
		"category": "heal",
		"cost": 1,
		"damage": 15,
		"desc": "거대한 무 대포탄을 발사하여 착탄 지점에 15 폭발 피해를 입힙니다.",
		"icon": "res://assets/05_회복_치유/radish_무/radish_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마": {
		"word": "마",
		"name": "마 (산약/마비침)",
		"category": "heal",
		"cost": 1,
		"damage": 12,
		"desc": "적의 급소에 마비 침을 발사하여 12 피해 및 1초간 마비(스턴)를 줍니다.",
		"icon": "res://assets/05_회복_치유/yam_마/yam_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"묵": {
		"word": "묵",
		"name": "묵 (도토리묵/슬로우)",
		"category": "heal",
		"cost": 1,
		"damage": 10,
		"desc": "끈적한 도토리묵을 뿜어 10 피해 및 적 이동속도를 60% 감속시킵니다.",
		"icon": "res://assets/05_회복_치유/jelly_묵/jelly_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"약": {
		"word": "약",
		"name": "약 (약초/치유광선)",
		"category": "heal",
		"cost": 1,
		"damage": 12,
		"desc": "치유의 약초 광선을 발사하여 12 피해를 입힙니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"북": {
		"word": "북",
		"name": "북 (전쟁의북/고동)",
		"category": "skill",
		"cost": 1,
		"damage": 10,
		"desc": "둥둥 울리는 북소리로 10 음파 피해 및 주변 아군 타워 공속을 +40% 가속합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"기": {
		"word": "기",
		"name": "기 (기공/관통기공파)",
		"category": "skill",
		"cost": 1,
		"damage": 20,
		"desc": "일직선상 모든 적을 관통하는 푸른 기공파로 20 관통 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"속": {
		"word": "속",
		"name": "속 (속도/고속연사)",
		"category": "skill",
		"cost": 1,
		"damage": 8,
		"rapid_fire": true,
		"desc": "공격 쿨타임 0.25초로 초당 4회 이상의 고속 활자 난사를 퍼붓습니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"능": {
		"word": "능",
		"name": "능 (능력/마력증폭)",
		"category": "skill",
		"cost": 1,
		"damage": 16,
		"desc": "마력 표식을 남겨 대상이 받는 모든 타워 피해를 +30% 증폭시킵니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"망": {
		"word": "망",
		"name": "망 (포획망/속박)",
		"category": "skill",
		"cost": 1,
		"damage": 14,
		"desc": "올가미 그물을 투척하여 14 피해 및 적들을 1.2초간 속박합니다.",
		"icon": "res://assets/06_버프_유틸/net_망/net_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"불꽃": {
		"word": "불꽃",
		"name": "불꽃 (화염/폭발)",
		"category": "element",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 24의 강력한 광역 화염 폭발을 일으키고 적들을 불태웁니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"얼음": {
		"word": "얼음",
		"name": "얼음 (빙결/극대둔화)",
		"category": "element",
		"cost": 2,
		"damage": 18,
		"desc": "[2글자 상위 타워] 18의 냉기 폭풍을 쏟아부어 범위 내 적들을 75% 극대 감속시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화살": {
		"word": "화살",
		"name": "화살 (원거리/저격)",
		"category": "weapon",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 사거리 220px의 초장거리에서 22의 정확한 저격 화살을 연속 발사합니다.",
		"icon": "res://assets/01_무기_공격/bow_활/bow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"검술": {
		"word": "검술",
		"name": "검술 (도검/연속베기)",
		"category": "weapon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 화려한 2연속 참격을 펼쳐 적들에게 26의 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성벽": {
		"word": "성벽",
		"name": "성벽 (방어/요새포)",
		"category": "defense",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 22의 요새 방어탄을 발사하며 사거리 내 진입한 적들의 속도를 50% 감속시킵니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"벼락": {
		"word": "벼락",
		"name": "벼락 (원소/연쇄감전)",
		"category": "element",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 하늘에서 벼락을 내리꽂아 30 번개 피해 및 최대 3체 적에게 연쇄 감전을 줍니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"폭풍": {
		"word": "폭풍",
		"name": "폭풍 (바람/광역넉백)",
		"category": "element",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 거대한 회오리바람으로 22 풍속 피해 및 범위 내 적들을 뒤로 강하게 밀어냅니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"바람": {
		"word": "바람",
		"name": "바람 (자연/신속관통)",
		"category": "element",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 날카로운 진공 칼날 3연발을 발사하여 일직선상의 적들을 관통합니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"치유": {
		"word": "치유",
		"name": "치유 (회복/성역포격)",
		"category": "heal",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 20의 성스러운 빛을 폭격하며, 매 웨이브 클리어 시 기지 HP를 +2 추가 회복합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"생명": {
		"word": "생명",
		"name": "생명 (회복/영혼흡수)",
		"category": "heal",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 22의 강력한 영혼 흡수탄을 쏘아 기지 최대 체력을 +5 영구 증가시킵니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"맹독": {
		"word": "맹독",
		"name": "맹독 (원소/치명부식)",
		"category": "element",
		"cost": 2,
		"damage": 16,
		"desc": "[2글자 상위 타워] 16의 부식성 산성액을 투척하여 적들에게 초당 8의 치명적인 독 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/poison_독/poison_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마법": {
		"word": "마법",
		"name": "마법 (비전/마력유도)",
		"category": "skill",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 적을 추적하는 3개의 마력 유도탄을 발사하여 25의 강력한 비전 피해를 줍니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"보물": {
		"word": "보물",
		"name": "보물 (유틸/황금포격)",
		"category": "skill",
		"cost": 2,
		"damage": 18,
		"desc": "[2글자 상위 타워] 18의 황금 코인 탄환을 발사하며 이 타워가 적을 처치하면 2배의 골드를 획득합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"강철": {
		"word": "강철",
		"name": "강철 (방어/강철포)",
		"category": "defense",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 26의 단단한 강철 볼트를 발사하여 일직선상의 적들을 분쇄합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화염": {
		"word": "화염",
		"name": "화염 (원소/업화폭발)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 작열하는 거대 화염구를 투척하여 반경 내 적들에게 28 화염 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"단검": {
		"word": "단검",
		"name": "단검 (암살/급소찌르기)",
		"category": "weapon",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 적의 약점을 찔러 24의 치명적인 암살 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/blade_도/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"장검": {
		"word": "장검",
		"name": "장검 (검술/회전베기)",
		"category": "weapon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 긴 칼날을 크게 휘둘러 주변 적들에게 25의 광역 베기 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"쌍검": {
		"word": "쌍검",
		"name": "쌍검 (난무/초고속)",
		"category": "weapon",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 두 자루의 검으로 초당 3회 이상의 연속 참격을 퍼붓습니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"비검": {
		"word": "비검",
		"name": "비검 (어검/비상검기)",
		"category": "weapon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 공중을 가르는 비검을 날려 원거리의 적을 27 피해로 관통합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"비도": {
		"word": "비도",
		"name": "비도 (투척/표창난사)",
		"category": "weapon",
		"cost": 2,
		"damage": 21,
		"desc": "[2글자 상위 타워] 날카로운 비도 4자루를 사방으로 투척하여 다수의 적을 요격합니다.",
		"icon": "res://assets/01_무기_공격/blade_도/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"거검": {
		"word": "거검",
		"name": "거검 (중검/대지분쇄)",
		"category": "weapon",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 육중한 거검으로 땅을 내리쳐 32의 파괴적인 충격파를 발생시킵니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"창술": {
		"word": "창술",
		"name": "창술 (장창/연속찌르기)",
		"category": "weapon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 화려한 창술로 전방 3개 라인의 적을 26 피해로 꿰뚫습니다.",
		"icon": "res://assets/01_무기_공격/spear_창/spear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"투석": {
		"word": "투석",
		"name": "투석 (공성/거석투척)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 거대한 투석기로 바위를 날려 착탄 지점에 28의 광역 폭발을 일으킵니다.",
		"icon": "res://assets/01_무기_공격/flail_추/flail_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"철퇴": {
		"word": "철퇴",
		"name": "철퇴 (강타/광역기절)",
		"category": "weapon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 가시 박힌 거대 철퇴를 휘둘러 27 피해 및 1초간 기절시킵니다.",
		"icon": "res://assets/01_무기_공격/mace_골/mace_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"암기": {
		"word": "암기",
		"name": "암기 (독침/맹독암기)",
		"category": "weapon",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 독이 묻은 은침을 연사하여 20 피해 및 중독(초당 6 피해)을 겁니다.",
		"icon": "res://assets/01_무기_공격/spike_못/spike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"사격": {
		"word": "사격",
		"name": "사격 (원거리/정밀저격)",
		"category": "weapon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 초정밀 사격으로 적의 헤드샷을 노려 26 관통 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/gun_총/gun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"난무": {
		"word": "난무",
		"name": "난무 (무술/광란타격)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 전방에 무자비한 난무를 펼쳐 28 다단히트 피해를 쏟아붓습니다.",
		"icon": "res://assets/01_무기_공격/fist_권/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"참격": {
		"word": "참격",
		"name": "참격 (검기/초승달검기)",
		"category": "weapon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 초승달 모양의 푸른 검기를 날려 경로 상의 모든 적을 베어냅니다.",
		"icon": "res://assets/01_무기_공격/wind_slash_삭/wind_slash_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"격투": {
		"word": "격투",
		"name": "격투 (권법/충격타)",
		"category": "weapon",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 단단한 권법 연격으로 23 피해와 함께 적을 뒤로 튕겨냅니다.",
		"icon": "res://assets/01_무기_공격/fist_권/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"일격": {
		"word": "일격",
		"name": "일격 (필살/혼신의일격)",
		"category": "weapon",
		"cost": 2,
		"damage": 35,
		"desc": "[2글자 상위 타워] 혼신의 기력을 모아 35의 압도적인 단일 치명타를 작렬합니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"분쇄": {
		"word": "분쇄",
		"name": "분쇄 (파쇄/방어관통)",
		"category": "weapon",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 적의 방어구를 박살내며 29의 묵직한 분쇄 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/axe_도끼/axe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"관통": {
		"word": "관통",
		"name": "관통 (투창/직선관통)",
		"category": "weapon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 일직선상 모든 적을 꿰뚫는 강력한 투창으로 27 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/spear_창/spear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"돌격": {
		"word": "돌격",
		"name": "돌격 (전진/돌파타격)",
		"category": "weapon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 적진으로 거침없이 돌격하여 26 피해 및 광역 경직을 일으킵니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"맹공": {
		"word": "맹공",
		"name": "맹공 (연타/노도)",
		"category": "weapon",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 노도와 같은 맹공으로 적들을 쉴 새 없이 몰아붙여 30 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"격파": {
		"word": "격파",
		"name": "격파 (강타/방벽파괴)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 적의 전열을 무너뜨리는 강력한 파괴타로 28 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/iron_쇠/iron_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙결": {
		"word": "빙결",
		"name": "빙결 (냉기/절대동결)",
		"category": "element",
		"cost": 2,
		"damage": 21,
		"desc": "[2글자 상위 타워] 적 피격 시 즉시 1.5초간 완전 동결(빙결 정지)시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙산": {
		"word": "빙산",
		"name": "빙산 (거대빙하/낙하)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 거대한 빙산을 소환하여 적들 머리 위에 28 낙하 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"낙뢰": {
		"word": "낙뢰",
		"name": "낙뢰 (번개/푸른낙뢰)",
		"category": "element",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 하늘을 가르는 벼락으로 32 피해 및 감전 쇼크를 일으킵니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"전기": {
		"word": "전기",
		"name": "전기 (전격/고압전류)",
		"category": "element",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 고압 전류를 방출하여 주변 적들을 지속적으로 지져버립니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"돌풍": {
		"word": "돌풍",
		"name": "돌풍 (바람/고속절단)",
		"category": "element",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 칼날 같은 돌풍을 일으켜 22 피해 및 적 40% 감속을 겁니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"태풍": {
		"word": "태풍",
		"name": "태풍 (폭풍/거대선풍)",
		"category": "element",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 거대한 태풍의 눈을 소환하여 범위 내 적들을 빨아들이며 30 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"암흑": {
		"word": "암흑",
		"name": "암흑 (심연/어둠폭발)",
		"category": "element",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 심연의 어둠 에너지를 폭발시켜 26 마법 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/dark_암/dark_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"그림자": {
		"word": "그림자",
		"name": "그림자 (은신/암습광선)",
		"category": "element",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 그림자 속에서 뿜어져 나오는 24의 관통 레이저를 발사합니다.",
		"icon": "res://assets/03_원소_마법/dark_암/dark_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"용암": {
		"word": "용암",
		"name": "용암 (마그마/화염바닥)",
		"category": "element",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 바닥에 끓어오르는 용암 웅덩이를 깔아 초당 10의 화상 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마그마": {
		"word": "마그마",
		"name": "마그마 (지열/용암탄)",
		"category": "element",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 작열하는 마그마 덩어리를 투척하여 29 광역 화염 폭발을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"운석": {
		"word": "운석",
		"name": "운석 (메테오/소형운석)",
		"category": "element",
		"cost": 2,
		"damage": 34,
		"desc": "[2글자 상위 타워] 하늘에서 불타는 소형 운석을 떨어뜨려 34의 파괴적인 충격을 줍니다.",
		"icon": "res://assets/03_원소_마법/star_별/star_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"유성": {
		"word": "유성",
		"name": "유성 (별빛/유성우)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 반짝이는 유성 3발을 연속으로 쏟아부어 28 신성 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/star_별/star_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대지": {
		"word": "대지",
		"name": "대지 (지진/지면파쇄)",
		"category": "element",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 대지를 진동시켜 26 피해와 함께 범위 내 적들을 1초간 기절시킵니다.",
		"icon": "res://assets/03_원소_마법/earth_흙/earth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"지진": {
		"word": "지진",
		"name": "지진 (진동/대지충격파)",
		"category": "element",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 강력한 지진파를 일으켜 경로 상의 적들을 모두 넘어뜨립니다.",
		"icon": "res://assets/03_원소_마법/earth_흙/earth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"해일": {
		"word": "해일",
		"name": "해일 (거대파도/수류)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 거대한 해일을 몰고 와 적들을 쓸어버리며 28 피해 및 넉백을 줍니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"폭우": {
		"word": "폭우",
		"name": "폭우 (호우/수포격)",
		"category": "element",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 쏟아지는 폭우로 적들의 시야를 가리고 22 피해 및 50% 감속을 겁니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"눈보라": {
		"word": "눈보라",
		"name": "눈보라 (한파/동결풍)",
		"category": "element",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 살을 에는 눈보라를 뿜어 25 피해 및 적들의 공속/이속을 60% 깎습니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"안개": {
		"word": "안개",
		"name": "안개 (환영/혼란안개)",
		"category": "element",
		"cost": 2,
		"damage": 18,
		"desc": "[2글자 상위 타워] 짙은 안개를 피워올려 적들을 혼란에 빠뜨리고 18 지속 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"독안개": {
		"word": "독안개",
		"name": "독안개 (신화/부식절멸)",
		"category": "element",
		"cost": 3,
		"damage": 42,
		"desc": "[3글자 신화 타워] 전장 전체를 뒤덮는 맹독 안개로 모든 적에게 초당 12 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/poison_독/poison_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"산성": {
		"word": "산성",
		"name": "산성 (부식/방어파괴)",
		"category": "element",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 부식성 산성액을 뿜어 적의 방어력을 0으로 만들며 23 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/poison_독/poison_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"열기": {
		"word": "열기",
		"name": "열기 (폭염/열파)",
		"category": "element",
		"cost": 2,
		"damage": 21,
		"desc": "[2글자 상위 타워] 숨 막히는 열파를 방출하여 21 화염 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"한기": {
		"word": "한기",
		"name": "한기 (동토/서리)",
		"category": "element",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 서리 기운을 퍼뜨려 20 피해 및 적들을 둔화시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"광채": {
		"word": "광채",
		"name": "광채 (섬광/눈부심)",
		"category": "element",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 눈부신 성광을 터뜨려 적들을 실명시키고 25 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/light_빛/light_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"주문": {
		"word": "주문",
		"name": "주문 (비전/비전문자)",
		"category": "skill",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 고대 활자 주문을 영창하여 26의 마법 광역 폭격을 퍼붓습니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화구": {
		"word": "화구",
		"name": "화구 (화염탄/파이어볼)",
		"category": "element",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 거대한 파이어볼을 발사하여 착탄 지점에 27 화염 폭발을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙하": {
		"word": "빙하",
		"name": "빙하 (만년설/서리포)",
		"category": "element",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 만년설의 서리 대포를 발사하여 26 피해 및 강력한 결빙을 겁니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"태양": {
		"word": "태양",
		"name": "태양 (일광/태양폭풍)",
		"category": "element",
		"cost": 2,
		"damage": 33,
		"desc": "[2글자 상위 타워] 이글거리는 태양의 열기를 집중 조사하여 33 신성 화염 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/sun_해/sun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"달빛": {
		"word": "달빛",
		"name": "달빛 (월광/은빛마력)",
		"category": "element",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 은빛 월광 세례를 내려 25의 신비로운 마법 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/moon_달/moon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"철벽": {
		"word": "철벽",
		"name": "철벽 (방어/절대방패)",
		"category": "defense",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 25의 단단한 철벽 방어탄을 발사하여 적들을 확실하게 밀어냅니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"갑옷": {
		"word": "갑옷",
		"name": "갑옷 (중갑/가시반사)",
		"category": "defense",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 23의 중갑 파편을 난사하여 사방의 적들에게 물리 피해를 가합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"투구": {
		"word": "투구",
		"name": "투구 (방호/투구박치기)",
		"category": "defense",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 단단한 투구의 힘으로 22 피해 및 적을 1초간 기절시킵니다.",
		"icon": "res://assets/02_방어_장비/guard_완/guard_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"요새": {
		"word": "요새",
		"name": "요새 (거점/요새포격)",
		"category": "defense",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 요새의 거대 함포를 발사하여 28의 파괴적인 광역 포격을 가합니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"결계": {
		"word": "결계",
		"name": "결계 (마법장막/반사)",
		"category": "defense",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 마법 결계를 펼쳐 24 피해와 함께 적의 투사체를 차단합니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성채": {
		"word": "성채",
		"name": "성채 (방벽/성채수호)",
		"category": "defense",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 성채의 수호포를 쏘아올려 26의 묵직한 포탄을 쏟아붓습니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"관문": {
		"word": "관문",
		"name": "관문 (철문/철문압살)",
		"category": "defense",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 육중한 관문 철문을 떨어뜨려 25 피해 및 범위 기절을 일으킵니다.",
		"icon": "res://assets/02_방어_장비/gate_문/gate_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"장벽": {
		"word": "장벽",
		"name": "장벽 (방어선/봉쇄)",
		"category": "defense",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 거대한 방어 장벽을 형성하여 적들의 진격을 24 피해로 저지합니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"수호": {
		"word": "수호",
		"name": "수호 (가호/수호빛)",
		"category": "defense",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 수호의 빛을 방출하여 25 피해 및 아군 타워 공격속도를 +20% 버프합니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"보호": {
		"word": "보호",
		"name": "보호 (보호막/정화)",
		"category": "defense",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 보호의 파동을 일으켜 23 피해 및 기지 피해를 1회 흡수합니다.",
		"icon": "res://assets/02_방어_장비/guard_완/guard_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"금강": {
		"word": "금강",
		"name": "금강 (불괴/금강석)",
		"category": "defense",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 다이아몬드처럼 단단한 금강 탄환으로 30의 파괴 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"석벽": {
		"word": "석벽",
		"name": "석벽 (돌벽/낙석)",
		"category": "defense",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 단단한 석벽에서 거대한 바위를 던져 24 광역 피해를 줍니다.",
		"icon": "res://assets/02_방어_장비/mountain_산/mountain_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"보루": {
		"word": "보루",
		"name": "보루 (최후보루/일제사격)",
		"category": "defense",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 최후의 보루에서 일제 사격을 퍼부어 27의 집중 포화를 가합니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"늑대": {
		"word": "늑대",
		"name": "늑대 (야수/연속도약)",
		"category": "summon",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 사나운 늑대를 소환하여 23의 날카로운 이빨로 물어뜯습니다.",
		"icon": "res://assets/04_생물_소환/wolf_늑/wolf_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"여우": {
		"word": "여우",
		"name": "여우 (요호/여우불)",
		"category": "summon",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 푸른 여우불 3개를 날려 22의 마법 화염 피해를 가합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"표범": {
		"word": "표범",
		"name": "표범 (맹수/초고속기습)",
		"category": "summon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 바람처럼 빠른 표범의 발톱으로 26 피해를 순식간에 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"독수리": {
		"word": "독수리",
		"name": "독수리 (맹금/급강하)",
		"category": "summon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 하늘에서 급강하하여 25의 강력한 발톱 낚아채기 공격을 가합니다.",
		"icon": "res://assets/04_생물_소환/bird_새/bird_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"거미": {
		"word": "거미",
		"name": "거미 (독거미/거미줄)",
		"category": "summon",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 끈끈한 거미줄과 맹독을 뿜어 20 피해 및 60% 슬로우를 겁니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"전갈": {
		"word": "전갈",
		"name": "전갈 (맹독/독침찌르기)",
		"category": "summon",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 날카로운 전갈 꼬리로 24 피해 및 초당 7의 치명상을 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"살무사": {
		"word": "살무사",
		"name": "살무사 (독사/맹독분사)",
		"category": "summon",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 살무사의 독액을 뿜어내어 23 피해 및 광역 부식 독을 퍼뜨립니다.",
		"icon": "res://assets/04_생물_소환/snake_뱀/snake_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"구렁이": {
		"word": "구렁이",
		"name": "구렁이 (대사/조르기)",
		"category": "summon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 거대한 구렁이로 적을 휘감아 25 피해 및 1.5초간 행동 불능으로 만듭니다.",
		"icon": "res://assets/04_생물_소환/snake_뱀/snake_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"호랑": {
		"word": "호랑",
		"name": "호랑 (맹호/호포)",
		"category": "summon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 맹호의 기백으로 전방을 덮쳐 28 물리 분쇄 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"사자": {
		"word": "사자",
		"name": "사자 (백수의왕/사자후)",
		"category": "summon",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 천지를 뒤흔드는 사자후를 내질러 29 광역 음파 피해 및 공포를 겁니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"코끼리": {
		"word": "코끼리",
		"name": "코끼리 (거수/대지짓밟기)",
		"category": "summon",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 거대한 코끼리의 발로 쿵 짓밟아 32의 파괴적인 충격파를 줍니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"황소": {
		"word": "황소",
		"name": "황소 (우각/돌진격돌)",
		"category": "summon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 성난 황소의 돌진으로 27 피해 및 적들을 시원하게 날려버립니다.",
		"icon": "res://assets/04_생물_소환/bull_소/bull_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"악어": {
		"word": "악어",
		"name": "악어 (파충/데스로우)",
		"category": "summon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 거대한 악어의 턱으로 적을 물고 회전하여 28 피해를 가합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"괴수": {
		"word": "괴수",
		"name": "괴수 (거대마수/포효)",
		"category": "summon",
		"cost": 2,
		"damage": 31,
		"desc": "[2글자 상위 타워] 거대 괴수의 포효로 전방의 모든 적에게 31의 혼돈 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"익룡": {
		"word": "익룡",
		"name": "익룡 (비행수/바람칼날)",
		"category": "summon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 하늘을 날며 거대한 날개 바람으로 25 풍속 관통 피해를 줍니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"골렘": {
		"word": "골렘",
		"name": "골렘 (바위거인/지면타격)",
		"category": "summon",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 바위 골렘이 지면을 내리쳐 30 물리 광역 피해 및 기절을 일으킵니다.",
		"icon": "res://assets/04_생물_소환/golem_골렘/golem_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"정령": {
		"word": "정령",
		"name": "정령 (원소/정령탄)",
		"category": "summon",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 원소 정령이 24의 순수한 마력 구체를 날려 적을 타격합니다.",
		"icon": "res://assets/04_생물_소환/spirit_정령/spirit_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"요정": {
		"word": "요정",
		"name": "요정 (빛의요정/신성탄)",
		"category": "summon",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 빛의 요정이 22 신성 유도탄을 쏘며 아군 공속을 +20% 버프합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"도깨비": {
		"word": "도깨비",
		"name": "도깨비 (도깨비방망이/뚝딱)",
		"category": "summon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 도깨비방망이로 내려쳐 28 피해 및 금은보화(추가 골드)를 드롭시킵니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"해골": {
		"word": "해골",
		"name": "해골 (언데드/뼈창투척)",
		"category": "summon",
		"cost": 2,
		"damage": 21,
		"desc": "[2글자 상위 타워] 해골 병사가 21의 날카로운 뼈창을 던져 관통 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"회복": {
		"word": "회복",
		"name": "회복 (재생/생명샘)",
		"category": "heal",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 20의 마법탄을 발사하며 매 초마다 기지 주변에 치유 오라를 방출합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성역": {
		"word": "성역",
		"name": "성역 (신성/결계축복)",
		"category": "heal",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 성역의 결계를 세워 24 신성 피해 및 아군 타워 공격력을 +20% 버프합니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"치료": {
		"word": "치료",
		"name": "치료 (약제/정화사격)",
		"category": "heal",
		"cost": 2,
		"damage": 19,
		"desc": "[2글자 상위 타워] 치료의 영약을 투척하여 19 피해 및 적들의 모든 버프를 해제합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"샘물": {
		"word": "샘물",
		"name": "샘물 (영천/청량폭격)",
		"category": "heal",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 맑은 영천수를 쏘아올려 22 광역 피해 및 적들을 40% 감속시킵니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"축복": {
		"word": "축복",
		"name": "축복 (신의가호/광휘)",
		"category": "heal",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 신의 축복 빛을 내리쬐어 25 신성 피해 및 아군 타워 사거리를 +30px 늘립니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"가호": {
		"word": "가호",
		"name": "가호 (수호신/보호막)",
		"category": "heal",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 신성한 가호로 23 피해를 가하고 기지 체력 +1 회복 기회를 얻습니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"재생": {
		"word": "재생",
		"name": "재생 (활력/초생)",
		"category": "heal",
		"cost": 2,
		"damage": 21,
		"desc": "[2글자 상위 타워] 활력의 초생수를 뿜어 21 피해 및 기지 HP 재생력을 강화합니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성수": {
		"word": "성수",
		"name": "성수 (정화수/악마퇴치)",
		"category": "heal",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 성수를 뿌려 26의 강력한 언데드/마수 퇴치 피해를 입힙니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"기적": {
		"word": "기적",
		"name": "기적 (은총/대역전)",
		"category": "heal",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 기적의 빛을 쏟아부어 30의 강력한 신성 피해를 입힙니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"정화": {
		"word": "정화",
		"name": "정화 (소멸/해악정화)",
		"category": "heal",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 모든 사악한 기운을 정화하는 24의 광휘 레이저를 발사합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"가속": {
		"word": "가속",
		"name": "가속 (질주/공속극대화)",
		"category": "skill",
		"cost": 2,
		"damage": 20,
		"rapid_fire": true,
		"desc": "[2글자 상위 타워] 20 피해를 입히며 주변 아군 타워 공격속도를 +50% 폭발적으로 증가시킵니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신속": {
		"word": "신속",
		"name": "신속 (초고속/광속탄)",
		"category": "skill",
		"cost": 2,
		"damage": 18,
		"rapid_fire": true,
		"desc": "[2글자 상위 타워] 공격 쿨타임 0.20초로 초당 5회 이상의 광속 탄환을 난사합니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"돌파": {
		"word": "돌파",
		"name": "돌파 (강행돌파/파쇄)",
		"category": "skill",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 적의 방어선을 단숨에 돌파하여 26 관통 물리 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"기운": {
		"word": "기운",
		"name": "기운 (영기/기공폭발)",
		"category": "skill",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 응축된 기운을 폭발시켜 27의 강력한 영기 충격파를 발생시킵니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"패기": {
		"word": "패기",
		"name": "패기 (위압/적공격무력)",
		"category": "skill",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 패왕의 위압감으로 적들을 짓눌러 28 피해 및 1초간 이동을 정지시킵니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"분노": {
		"word": "분노",
		"name": "분노 (격노/피해증폭)",
		"category": "skill",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 타오르는 분노로 공격력이 극대화된 32의 격노탄을 발사합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"집중": {
		"word": "집중",
		"name": "집중 (명경지수/치명타)",
		"category": "skill",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 극도의 집중력으로 100% 치명타율의 28 정밀 탄환을 쏩니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"황금": {
		"word": "황금",
		"name": "황금 (골드/황금벼락)",
		"category": "skill",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 황금빛 벼락을 내리쳐 22 피해 및 처치 시 골드 드롭량을 2.5배로 늘립니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"약탈": {
		"word": "약탈",
		"name": "약탈 (노획/골드강탈)",
		"category": "skill",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 적을 타격할 때마다 1G씩 골드를 강탈하며 24 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/net_망/net_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"도약": {
		"word": "도약",
		"name": "도약 (비상/공중폭격)",
		"category": "skill",
		"cost": 2,
		"damage": 25,
		"rapid_fire": true,
		"desc": "[2글자 상위 타워] 하늘 높이 도약하여 착지 지점에 25의 강력한 충격파를 줍니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"징벌": {
		"word": "징벌",
		"name": "징벌 (심판/신의철퇴)",
		"category": "skill",
		"cost": 2,
		"damage": 31,
		"desc": "[2글자 상위 타워] 신의 징벌 철퇴를 내리쳐 31의 압도적인 단일 파쇄 피해를 가합니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"진격": {
		"word": "진격",
		"name": "진격 (돌격명령/사기충천)",
		"category": "skill",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 진격 나팔을 불어 26 피해 및 전 타워 공격력을 +15% 증가시킵니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"승리": {
		"word": "승리",
		"name": "승리 (승전보/환호)",
		"category": "skill",
		"cost": 2,
		"damage": 33,
		"desc": "[2글자 상위 타워] 승리의 축포를 쏘아올려 33 광역 폭발 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"명중": {
		"word": "명중",
		"name": "명중 (필중/백발백중)",
		"category": "skill",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 절대 빗나가지 않는 필중의 화살로 27 관통 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마수": {
		"word": "마수",
		"name": "마수 (마물/암흑발톱)",
		"category": "summon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 포악한 마수를 불러내어 27의 어둠 발톱 공격을 가합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"귀신": {
		"word": "귀신",
		"name": "귀신 (원혼/빙의저주)",
		"category": "summon",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 원혼의 저주를 내려 24 피해 및 적 공격력을 40% 약화시킵니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"망령": {
		"word": "망령",
		"name": "망령 (유령/공포비명)",
		"category": "summon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 망령의 날카로운 비명으로 25 정신 피해 및 적들을 1초간 공포에 빠뜨립니다.",
		"icon": "res://assets/04_생물_소환/spirit_정령/spirit_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"요괴": {
		"word": "요괴",
		"name": "요괴 (환술/혼돈술)",
		"category": "summon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 요괴의 환술로 적들의 경로를 헝클어뜨리며 26 혼돈 피해를 줍니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"괴물": {
		"word": "괴물",
		"name": "괴물 (이형/거대촉수)",
		"category": "summon",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 이형의 거대 촉수를 휘둘러 29 광역 타격을 입힙니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"용가리": {
		"word": "용가리",
		"name": "용가리 (새끼용/용화염)",
		"category": "summon",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 용가리의 맹렬한 아기 화염포로 30 지속 피해를 가합니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"매화": {
		"word": "매화",
		"name": "매화 (꽃잎/선혈검)",
		"category": "weapon",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 흩날리는 매화 꽃잎처럼 화려한 25 참격을 펼칩니다.",
		"icon": "res://assets/01_무기_공격/blade_도/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"백발": {
		"word": "백발",
		"name": "백발 (백발백중/명궁)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 백발백중의 신궁 사격으로 28의 치명적 관통탄을 쏩니다.",
		"icon": "res://assets/01_무기_공격/bow_활/bow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화포": {
		"word": "화포",
		"name": "화포 (함포/대포연사)",
		"category": "weapon",
		"cost": 2,
		"damage": 31,
		"desc": "[2글자 상위 타워] 육중한 화포를 연속 발사하여 31의 파괴적인 포격을 쏟아붓습니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"폭약": {
		"word": "폭약",
		"name": "폭약 (지뢰/폭탄설치)",
		"category": "element",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 적의 길목에 폭약을 매설하여 30의 강력한 연쇄 폭발을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/explosion_폭/explosion_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"냉기": {
		"word": "냉기",
		"name": "냉기 (극저온/서리폭풍)",
		"category": "element",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 극저온 냉기를 뿜어 23 피해 및 광역 50% 둔화를 겁니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"광선": {
		"word": "광선",
		"name": "광선 (레이저/집중조사)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 고에너지 마력 광선을 집중 조사하여 28의 지속 관통 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/light_빛/light_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"섬광": {
		"word": "섬광",
		"name": "섬광 (백색광/실명폭탄)",
		"category": "element",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 백색 섬광탄을 터뜨려 26 피해 및 적들의 시야를 앗아갑니다.",
		"icon": "res://assets/03_원소_마법/light_빛/light_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화마": {
		"word": "화마",
		"name": "화마 (불도깨비/화염쇄도)",
		"category": "element",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 화마의 거대한 불길이 쇄도하여 32의 압도적 화염을 뿌립니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙마": {
		"word": "빙마",
		"name": "빙마 (얼음귀신/혹한)",
		"category": "element",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 빙마의 혹한 폭풍으로 29 냉기 피해 및 결빙을 일으킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"뇌우": {
		"word": "뇌우",
		"name": "뇌우 (번개비/전기폭풍)",
		"category": "element",
		"cost": 2,
		"damage": 31,
		"desc": "[2글자 상위 타워] 번개를 동반한 뇌우를 내려쳐 31의 광역 감전 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"암석": {
		"word": "암석",
		"name": "암석 (바위탄/거석강타)",
		"category": "element",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 단단한 거대 암석을 투척하여 27 물리 충격파를 발생시킵니다.",
		"icon": "res://assets/03_원소_마법/earth_흙/earth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"흑요": {
		"word": "흑요",
		"name": "흑요 (흑요석/암흑결정)",
		"category": "element",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 날카로운 흑요석 파편을 난사하여 28 출혈 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/dark_암/dark_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신검": {
		"word": "신검",
		"name": "신검 (전설검/빛의검기)",
		"category": "weapon",
		"cost": 2,
		"damage": 34,
		"desc": "[2글자 상위 타워] 전설의 신검에서 뿜어져 나오는 34의 눈부신 성검기를 날립니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마검": {
		"word": "마검",
		"name": "마검 (저주검/영혼베기)",
		"category": "weapon",
		"cost": 2,
		"damage": 33,
		"desc": "[2글자 상위 타워] 피를 갈구하는 마검으로 적의 영혼을 베어 33 암흑 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"보검": {
		"word": "보검",
		"name": "보검 (보물검/보석참격)",
		"category": "weapon",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 보석이 박힌 보검으로 30 피해 및 추가 골드를 획득합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"흑철": {
		"word": "흑철",
		"name": "흑철 (흑철괴/암석분쇄)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 무거운 흑철 둔기로 적의 뼈를 부수며 28 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/iron_쇠/iron_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"은화": {
		"word": "은화",
		"name": "은화 (은전/은화투척)",
		"category": "skill",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 날카롭게 연마된 은화를 연속 투척하여 22 피해를 줍니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"백금": {
		"word": "백금",
		"name": "백금 (플래티넘/금속결계)",
		"category": "defense",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 귀한 백금 방벽을 세워 29 피해 및 적의 접근을 차단합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"청동": {
		"word": "청동",
		"name": "청동 (청동방패/충격반사)",
		"category": "defense",
		"cost": 2,
		"damage": 23,
		"desc": "[2글자 상위 타워] 단단한 청동 방패로 23 충격파를 발사해 적을 튕겨냅니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"강습": {
		"word": "강습",
		"name": "강습 (급습/공중강습)",
		"category": "weapon",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 공중에서 적진 한가운데로 강습하여 29 광역 분쇄를 일으킵니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"습격": {
		"word": "습격",
		"name": "습격 (기습/어둠습격)",
		"category": "weapon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 어둠 속에서 불시에 습격하여 27의 기습 치명타를 입힙니다.",
		"icon": "res://assets/01_무기_공격/blade_도/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"포격": {
		"word": "포격",
		"name": "포격 (집중포화/함포사격)",
		"category": "weapon",
		"cost": 2,
		"damage": 33,
		"desc": "[2글자 상위 타워] 화력 집중 포격을 퍼부어 33의 무자비한 폭격을 가합니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"난격": {
		"word": "난격",
		"name": "난격 (연타/폭풍난타)",
		"category": "weapon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 폭풍 같은 주먹 난타로 28 다단히트 피해를 쏟아붓습니다.",
		"icon": "res://assets/01_무기_공격/fist_권/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"압살": {
		"word": "압살",
		"name": "압살 (압축/지면압살)",
		"category": "weapon",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 적을 바닥으로 짓눌러 32의 파괴적인 압살 피해를 줍니다.",
		"icon": "res://assets/01_무기_공격/mace_골/mace_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"절단": {
		"word": "절단",
		"name": "절단 (예기/단면절단)",
		"category": "weapon",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 극상의 예리함으로 적의 신체를 29 피해로 단숨에 절단합니다.",
		"icon": "res://assets/01_무기_공격/scythe_낫/scythe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"격멸": {
		"word": "격멸",
		"name": "격멸 (소탕/섬멸사격)",
		"category": "weapon",
		"cost": 2,
		"damage": 34,
		"desc": "[2글자 상위 타워] 적 무리를 일거에 격멸하는 34의 섬멸 탄환을 발사합니다.",
		"icon": "res://assets/01_무기_공격/gun_총/gun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"섬멸": {
		"word": "섬멸",
		"name": "섬멸 (일소/전장청소)",
		"category": "weapon",
		"cost": 2,
		"damage": 35,
		"desc": "[2글자 상위 타워] 전장의 적들을 일소하는 35의 강력한 파괴 광선을 쏩니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"파괴": {
		"word": "파괴",
		"name": "파괴 (붕괴/구조파괴)",
		"category": "weapon",
		"cost": 2,
		"damage": 31,
		"desc": "[2글자 상위 타워] 적의 진형을 완전히 붕괴시키며 31 파쇄 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/axe_도끼/axe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"소탕": {
		"word": "소탕",
		"name": "소탕 (청소/광역제압)",
		"category": "weapon",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 전방의 잔챙이들을 27 광역 공격으로 말끔히 소탕합니다.",
		"icon": "res://assets/01_무기_공격/spear_창/spear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"수호자": {
		"word": "수호자",
		"name": "수호자 (가호/수호결계)",
		"category": "defense",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 수호자의 신성한 방패로 28 피해 및 아군을 보호합니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"보호막": {
		"word": "보호막",
		"name": "보호막 (실드/피해흡수)",
		"category": "defense",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 푸른 보호막을 전개하여 25 피해 및 기지 피해를 방어합니다.",
		"icon": "res://assets/02_방어_장비/guard_완/guard_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"방벽": {
		"word": "방벽",
		"name": "방벽 (장벽/돌벽방어)",
		"category": "defense",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 높은 방벽을 축조하여 26 피해 및 적들의 길을 막아섭니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"철갑": {
		"word": "철갑",
		"name": "철갑 (중무장/철갑관통)",
		"category": "defense",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 육중한 철갑을 두른 채 27의 묵직한 가시 파편을 발사합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"요새탑": {
		"word": "요새탑",
		"name": "요새탑 (포탑/자동사격)",
		"category": "defense",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 요새 탑에 장착된 발리스타로 30의 강력한 볼트를 연사합니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성문": {
		"word": "성문",
		"name": "성문 (철통/성문낙하)",
		"category": "defense",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 거대한 성문을 쾅 내리찍어 28 피해 및 광역 기절을 줍니다.",
		"icon": "res://assets/02_방어_장비/gate_문/gate_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"진지": {
		"word": "진지",
		"name": "진지 (거점/화력진지)",
		"category": "defense",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 단단한 화력 진지에서 29의 집중 사격을 쏟아냅니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"초소": {
		"word": "초소",
		"name": "초소 (감시/전방초소)",
		"category": "defense",
		"cost": 2,
		"damage": 24,
		"desc": "[2글자 상위 타워] 전방 감시 초소에서 24의 빠른 경계 사격을 가합니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"망루": {
		"word": "망루",
		"name": "망루 (저격망루/고공사격)",
		"category": "defense",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 높은 망루 위에서 27의 원거리 저격 화살을 쏩니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"해자": {
		"word": "해자",
		"name": "해자 (함정/물웅덩이)",
		"category": "defense",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 성벽 앞 깊은 해자로 적들을 빠뜨려 22 피해 및 60% 슬로우를 줍니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"함정": {
		"word": "함정",
		"name": "함정 (트랩/가시함정)",
		"category": "defense",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 바닥에 날카로운 가시 함정을 깔아 25 피해 및 발을 묶습니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"결전": {
		"word": "결전",
		"name": "결전 (최후결전/투혼)",
		"category": "skill",
		"cost": 2,
		"damage": 35,
		"desc": "[2글자 상위 타워] 최후의 결전을 선언하며 35의 극대화된 투혼 참격을 작렬합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"필살": {
		"word": "필살",
		"name": "필살 (극의/일격필살)",
		"category": "skill",
		"cost": 2,
		"damage": 36,
		"desc": "[2글자 상위 타워] 일격필살의 오의를 펼쳐 36의 치명적인 단일 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"오의": {
		"word": "오의",
		"name": "오의 (비기/문파오의)",
		"category": "skill",
		"cost": 2,
		"damage": 34,
		"desc": "[2글자 상위 타워] 비전 오의를 개방하여 34의 화려한 연환계를 가합니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"비기": {
		"word": "비기",
		"name": "비기 (비술/감춰진힘)",
		"category": "skill",
		"cost": 2,
		"damage": 32,
		"desc": "[2글자 상위 타워] 숨겨진 비기를 발동하여 32의 강력한 마력 폭풍을 일으킵니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"환상": {
		"word": "환상",
		"name": "환상 (신기루/환영분신)",
		"category": "skill",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 환영 분신을 만들어 적들을 현혹하고 26 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신기루": {
		"word": "신기루",
		"name": "신기루 (사막/신기루폭격)",
		"category": "skill",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 아지랑이 신기루 속에서 27의 기습 마법탄을 쏟아붓습니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"영혼": {
		"word": "영혼",
		"name": "영혼 (소울/영혼수확)",
		"category": "heal",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 적의 영혼을 수확하여 28 피해 및 기지 생명력을 보충합니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"축제": {
		"word": "축제",
		"name": "축제 (환호/황금축제)",
		"category": "skill",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 전장에 축제를 열어 25 피해 및 골드 획득량을 대폭 증가시킵니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"환호": {
		"word": "환호",
		"name": "환호 (사기/환호성)",
		"category": "skill",
		"cost": 2,
		"damage": 27,
		"desc": "[2글자 상위 타워] 아군의 사기를 드높이는 환호성으로 27 피해 및 전 타워 공속을 버프합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"함성": {
		"word": "함성",
		"name": "함성 (포효/전장의함성)",
		"category": "skill",
		"cost": 2,
		"damage": 29,
		"desc": "[2글자 상위 타워] 우렁찬 전장의 함성으로 29 광역 음파 충격을 가합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"호랑이": {
		"word": "호랑이",
		"name": "호랑이 (신화/맹호포효)",
		"category": "summon",
		"cost": 3,
		"damage": 50,
		"desc": "[3글자 신화 타워] 50의 압도적인 맹수 포효로 적들을 공포에 질리게 하고 전방을 도륙합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"불벼락": {
		"word": "불벼락",
		"name": "불벼락 (신화/화염낙뢰)",
		"category": "element",
		"cost": 3,
		"damage": 60,
		"desc": "[3글자 신화 타워] 하늘에서 거대한 화염 낙뢰를 연속 폭격하여 60의 초토화 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"폭풍우": {
		"word": "폭풍우",
		"name": "폭풍우 (신화/태풍폭우)",
		"category": "element",
		"cost": 3,
		"damage": 45,
		"desc": "[3글자 신화 타워] 거대한 태풍과 폭우를 소환하여 45 광역 피해 및 적들을 80% 봉쇄합니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"얼음검": {
		"word": "얼음검",
		"name": "얼음검 (신화/빙결참격)",
		"category": "weapon",
		"cost": 3,
		"damage": 42,
		"desc": "[3글자 신화 타워] 절대영도의 빙결검으로 적 피격 즉시 2초간 완전 동결(Stun)시킵니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"독화살": {
		"word": "독화살",
		"name": "독화살 (신화/치사맹독)",
		"category": "weapon",
		"cost": 3,
		"damage": 38,
		"desc": "[3글자 신화 타워] 38 저격 사격 및 초당 15의 치사량 맹독을 주입하여 적을 녹여버립니다.",
		"icon": "res://assets/01_무기_공격/bow_활/bow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대검술": {
		"word": "대검술",
		"name": "대검술 (신화/초대형검기)",
		"category": "weapon",
		"cost": 3,
		"damage": 55,
		"desc": "[3글자 신화 타워] 경로 위의 모든 적을 가르는 초대형 청색 검기로 55 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"용의숨": {
		"word": "용의숨",
		"name": "용의숨 (신화/드래곤브레스)",
		"category": "element",
		"cost": 3,
		"damage": 70,
		"desc": "[3글자 신화 타워] 전방 적을 잿더미로 만드는 70의 파괴적인 드래곤 브레스를 방출합니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"생명수": {
		"word": "생명수",
		"name": "생명수 (신화/기적폭격)",
		"category": "heal",
		"cost": 3,
		"damage": 45,
		"desc": "[3글자 신화 타워] 기지 체력 +5 즉시 회복 및 전 필드 아군 타워 공속을 +50% 버프합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"철옹성": {
		"word": "철옹성",
		"name": "철옹성 (신화/무적요새)",
		"category": "defense",
		"cost": 3,
		"damage": 48,
		"desc": "[3글자 신화 타워] 48의 무적 요새포 3연사를 발사하여 다가오는 적들을 산산조각 냅니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"불사조": {
		"word": "불사조",
		"name": "불사조 (신화/영생화염)",
		"category": "summon",
		"cost": 3,
		"damage": 58,
		"desc": "[3글자 신화 타워] 불사조를 소환하여 58의 영원히 꺼지지 않는 성스러운 화염을 쏟아붓습니다.",
		"icon": "res://assets/04_생물_소환/bird_새/bird_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"청룡검": {
		"word": "청룡검",
		"name": "청룡검 (신화/용검기)",
		"category": "weapon",
		"cost": 3,
		"damage": 62,
		"desc": "[3글자 신화 타워] 청룡의 기운이 깃든 신검으로 62의 용 형태 검기를 뿜어냅니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"백호랑": {
		"word": "백호랑",
		"name": "백호랑 (신화/신수백호)",
		"category": "summon",
		"cost": 3,
		"damage": 54,
		"desc": "[3글자 신화 타워] 신수 백호가 강림하여 54의 전방위 도륙 참격을 작렬합니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"현무암": {
		"word": "현무암",
		"name": "현무암 (신화/대지지진)",
		"category": "defense",
		"cost": 3,
		"damage": 52,
		"desc": "[3글자 신화 타워] 절대 깨지지 않는 현무 방벽으로 52 광역 지진 충격을 가합니다.",
		"icon": "res://assets/02_방어_장비/mountain_산/mountain_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"주작날": {
		"word": "주작날",
		"name": "주작날 (신화/주작화염)",
		"category": "element",
		"cost": 3,
		"damage": 56,
		"desc": "[3글자 신화 타워] 주작의 붉은 날갯짓으로 전장에 56의 화염 폭풍을 휘몰아칩니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"쌍검술": {
		"word": "쌍검술",
		"name": "쌍검술 (신화/극의난무)",
		"category": "weapon",
		"cost": 3,
		"damage": 48,
		"desc": "[3글자 신화 타워] 눈에 보이지 않는 속도로 48의 6연속 극의 참격을 난사합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대폭발": {
		"word": "대폭발",
		"name": "대폭발 (신화/메가익스플로전)",
		"category": "element",
		"cost": 3,
		"damage": 65,
		"desc": "[3글자 신화 타워] 화면 절반을 뒤덮는 65의 초대형 메가 폭발을 터뜨립니다.",
		"icon": "res://assets/03_원소_마법/explosion_폭/explosion_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성기사": {
		"word": "성기사",
		"name": "성기사 (신화/신의수호자)",
		"category": "defense",
		"cost": 3,
		"damage": 50,
		"desc": "[3글자 신화 타워] 50의 신성 철퇴 강타와 함께 전 타워에 피해 감소 보호막을 부여합니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"광전사": {
		"word": "광전사",
		"name": "광전사 (신화/피의광란)",
		"category": "weapon",
		"cost": 3,
		"damage": 58,
		"desc": "[3글자 신화 타워] 체력이 낮아질수록 공속이 2배 빨라지며 58의 광란 도끼질을 퍼붓습니다.",
		"icon": "res://assets/01_무기_공격/axe_도끼/axe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"궁술사": {
		"word": "궁술사",
		"name": "궁술사 (신화/신궁일발)",
		"category": "weapon",
		"cost": 3,
		"damage": 46,
		"desc": "[3글자 신화 타워] 사거리 260px에서 46의 마법 유도 화살 5발을 일제 사격합니다.",
		"icon": "res://assets/01_무기_공격/bow_활/bow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"천리안": {
		"word": "천리안",
		"name": "천리안 (신화/전맵저격)",
		"category": "skill",
		"cost": 3,
		"damage": 44,
		"desc": "[3글자 신화 타워] 맵 전체 어디든 적을 타겟팅하여 44의 관통 레이저를 발사합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"초고속": {
		"word": "초고속",
		"name": "초고속 (신화/광속머신건)",
		"category": "skill",
		"cost": 3,
		"damage": 35,
		"rapid_fire": true,
		"desc": "[3글자 신화 타워] 쿨타임 0.15초로 초당 7회 이상의 빛의 속도로 활자 탄환을 난사합니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마력포": {
		"word": "마력포",
		"name": "마력포 (신화/비전캐논)",
		"category": "skill",
		"cost": 3,
		"damage": 60,
		"desc": "[3글자 신화 타워] 거대한 비전 마력포를 발사하여 60의 파괴 광선을 뿜어냅니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"용기병": {
		"word": "용기병",
		"name": "용기병 (신화/드라군)",
		"category": "weapon",
		"cost": 3,
		"damage": 52,
		"desc": "[3글자 신화 타워] 용을 탄 기병이 52의 화염 장창으로 적진을 짓밟고 관통합니다.",
		"icon": "res://assets/01_무기_공격/spear_창/spear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"지옥불": {
		"word": "지옥불",
		"name": "지옥불 (신화/헬파이어)",
		"category": "element",
		"cost": 3,
		"damage": 66,
		"desc": "[3글자 신화 타워] 꺼지지 않는 지옥의 화염으로 66의 암흑 화염 피해를 퍼붓습니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙하기": {
		"word": "빙하기",
		"name": "빙하기 (신화/절대영도)",
		"category": "element",
		"cost": 3,
		"damage": 48,
		"desc": "[3글자 신화 타워] 전장에 빙하기를 불러와 모든 적의 이동속도를 70% 영구 감속시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"황금포": {
		"word": "황금포",
		"name": "황금포 (신화/황금대포)",
		"category": "skill",
		"cost": 3,
		"damage": 42,
		"desc": "[3글자 신화 타워] 42의 황금 포탄을 발사하며 적 처치 시 3배의 막대한 골드를 획득합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"승전가": {
		"word": "승전가",
		"name": "승전가 (신화/승리의함성)",
		"category": "skill",
		"cost": 3,
		"damage": 40,
		"desc": "[3글자 신화 타워] 40 음파 피해 및 전 필드 아군 타워 공격력을 +30% 영구 버프합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"일격필": {
		"word": "일격필",
		"name": "일격필 (신화/일격필살)",
		"category": "weapon",
		"cost": 3,
		"damage": 68,
		"desc": "[3글자 신화 타워] 단 한 번의 혼신의 일격으로 68의 극대 치명타 피해를 폭발시킵니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"백호수": {
		"word": "백호수",
		"name": "백호수 (신화/백호의발톱)",
		"category": "summon",
		"cost": 3,
		"damage": 52,
		"desc": "[3글자 신화 타워] 신수 백호의 신성한 발톱으로 52의 광역 열상을 남깁니다.",
		"icon": "res://assets/04_생물_소환/tiger_호/tiger_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"태양광": {
		"word": "태양광",
		"name": "태양광 (신화/태양의광휘)",
		"category": "element",
		"cost": 3,
		"damage": 64,
		"desc": "[3글자 신화 타워] 타오르는 태양의 광휘를 집중 방출하여 64의 거대한 신성 화염을 쏩니다.",
		"icon": "res://assets/03_원소_마법/sun_해/sun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"달빛검": {
		"word": "달빛검",
		"name": "달빛검 (신화/월광신검)",
		"category": "weapon",
		"cost": 3,
		"damage": 54,
		"desc": "[3글자 신화 타워] 은빛 월광의 검기로 54의 신비로운 마력 절단을 가합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"별똥별": {
		"word": "별똥별",
		"name": "별똥별 (신화/유성폭격)",
		"category": "element",
		"cost": 3,
		"damage": 58,
		"desc": "[3글자 신화 타워] 하늘에서 쏟아지는 별똥별 무리로 58의 화려한 광역 폭격을 퍼붓습니다.",
		"icon": "res://assets/03_원소_마법/star_별/star_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대지진": {
		"word": "대지진",
		"name": "대지진 (신화/지각붕괴)",
		"category": "element",
		"cost": 3,
		"damage": 60,
		"desc": "[3글자 신화 타워] 지각을 붕괴시키는 60의 파괴적 지진파로 모든 적을 넘어뜨립니다.",
		"icon": "res://assets/03_원소_마법/earth_흙/earth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"초태풍": {
		"word": "초태풍",
		"name": "초태풍 (신화/하이퍼태풍)",
		"category": "element",
		"cost": 3,
		"damage": 56,
		"desc": "[3글자 신화 타워] 거대한 초태풍으로 적들을 전장 밖으로 날려버릴 듯한 56 풍속 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대해일": {
		"word": "대해일",
		"name": "대해일 (신화/메가쓰나미)",
		"category": "element",
		"cost": 3,
		"damage": 55,
		"desc": "[3글자 신화 타워] 메가 쓰나미를 몰고 와 55 피해와 함께 적들을 시작 지점 쪽으로 밀쳐냅니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"화룡포": {
		"word": "화룡포",
		"name": "화룡포 (신화/화룡의대포)",
		"category": "weapon",
		"cost": 3,
		"damage": 65,
		"desc": "[3글자 신화 타워] 화룡의 형상을 띤 거대 포탄으로 65의 초열 폭발을 일으킵니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"뇌신포": {
		"word": "뇌신포",
		"name": "뇌신포 (신화/뇌신의번개)",
		"category": "element",
		"cost": 3,
		"damage": 62,
		"desc": "[3글자 신화 타워] 뇌신의 심판 번개 5발을 연속으로 내리쳐 62 감전 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/thunder_뇌/thunder_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"사신낫": {
		"word": "사신낫",
		"name": "사신낫 (신화/사신의대낫)",
		"category": "weapon",
		"cost": 3,
		"damage": 60,
		"desc": "[3글자 신화 타워] 사신의 거대한 대낫으로 60의 즉사급 암흑 영혼 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/scythe_낫/scythe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"금강석": {
		"word": "금강석",
		"name": "금강석 (신화/다이아몬드)",
		"category": "defense",
		"cost": 3,
		"damage": 55,
		"desc": "[3글자 신화 타워] 절대 부서지지 않는 금강석 장벽으로 55 피해 및 기지 완벽 방어를 구축합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"무적탑": {
		"word": "무적탑",
		"name": "무적탑 (신화/무적의요새)",
		"category": "defense",
		"cost": 3,
		"damage": 50,
		"desc": "[3글자 신화 타워] 절대 무적의 방어 탑에서 50의 연속 방어포를 난사합니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"황금용": {
		"word": "황금용",
		"name": "황금용 (신화/골든드래곤)",
		"category": "summon",
		"cost": 3,
		"damage": 75,
		"desc": "[3글자 신화 타워] 황금 드래곤이 강림하여 75의 눈부신 황금 브레스와 막대한 골드를 선사합니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신룡포": {
		"word": "신룡포",
		"name": "신룡포 (신화/신룡의포격)",
		"category": "weapon",
		"cost": 3,
		"damage": 72,
		"desc": "[3글자 신화 타워] 신룡의 마력을 실은 72의 초거대 포탄으로 전장을 초토화합니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마신검": {
		"word": "마신검",
		"name": "마신검 (신화/마신의저주)",
		"category": "weapon",
		"cost": 3,
		"damage": 66,
		"desc": "[3글자 신화 타워] 마신의 저주가 서린 참격으로 66의 암흑 화염 피해를 가합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"영웅검": {
		"word": "영웅검",
		"name": "영웅검 (신화/용사의성검)",
		"category": "weapon",
		"cost": 3,
		"damage": 64,
		"desc": "[3글자 신화 타워] 용사의 성검에서 뿜어지는 64의 눈부신 빛으로 적들을 일도양단합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"기적수": {
		"word": "기적수",
		"name": "기적수 (신화/기적의샘물)",
		"category": "heal",
		"cost": 3,
		"damage": 46,
		"desc": "[3글자 신화 타워] 기적의 성역을 펼쳐 46 피해 및 아군 전 타워를 완벽 강화합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"진군가": {
		"word": "진군가",
		"name": "진군가 (신화/진격의북소리)",
		"category": "skill",
		"cost": 3,
		"damage": 42,
		"desc": "[3글자 신화 타워] 웅장한 진군가로 42 음파 피해 및 전 타워 공격속도를 +40% 버프합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"대사격": {
		"word": "대사격",
		"name": "대사격 (신화/일제집중사격)",
		"category": "weapon",
		"cost": 3,
		"damage": 56,
		"desc": "[3글자 신화 타워] 전방위 일제 집중 사격으로 56의 화력 폭풍을 퍼붓습니다.",
		"icon": "res://assets/01_무기_공격/gun_총/gun_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"파천황": {
		"word": "파천황",
		"name": "파천황 (신화/천지개벽)",
		"category": "skill",
		"cost": 3,
		"damage": 70,
		"desc": "[3글자 신화 타워] 천지를 뒤흔드는 파천황의 일격으로 70의 파괴적인 혼돈 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"패왕격": {
		"word": "패왕격",
		"name": "패왕격 (신화/패왕의강타)",
		"category": "weapon",
		"cost": 3,
		"damage": 67,
		"desc": "[3글자 신화 타워] 패왕의 기백을 실은 67의 주먹 강타로 전방을 분쇄합니다.",
		"icon": "res://assets/01_무기_공격/fist_권/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"극마법": {
		"word": "극마법",
		"name": "극마법 (신화/궁극의마법)",
		"category": "skill",
		"cost": 3,
		"damage": 65,
		"desc": "[3글자 신화 타워] 5대 원소를 융합한 궁극의 비전 마법으로 65의 원소 폭격을 퍼붓습니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"절대자": {
		"word": "절대자",
		"name": "절대자 (신화/절대수호자)",
		"category": "defense",
		"cost": 3,
		"damage": 58,
		"desc": "[3글자 신화 타워] 절대자의 권능으로 58 피해 및 전장에 무적 보호막을 펼칩니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신수호": {
		"word": "신수호",
		"name": "신수호 (신화/신의가호)",
		"category": "defense",
		"cost": 3,
		"damage": 54,
		"desc": "[3글자 신화 타워] 신의 가호가 깃든 성스러운 방패로 54 피해 및 적들을 멀리 튕겨냅니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"초신성": {
		"word": "초신성",
		"name": "초신성 (신화/슈퍼노바)",
		"category": "element",
		"cost": 3,
		"damage": 72,
		"desc": "[3글자 신화 타워] 거대한 별의 폭발(슈퍼노바)로 72의 광대한 우주 파괴 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/star_별/star_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"암흑성": {
		"word": "암흑성",
		"name": "암흑성 (신화/블랙홀)",
		"category": "element",
		"cost": 3,
		"damage": 68,
		"desc": "[3글자 신화 타워] 모든 것을 빨아들이는 블랙홀을 생성하여 68의 지속 압축 피해를 가합니다.",
		"icon": "res://assets/03_원소_마법/dark_암/dark_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마도사": {
		"word": "마도사",
		"name": "마도사 (신화/대마도사)",
		"category": "skill",
		"cost": 3,
		"damage": 62,
		"desc": "[3글자 신화 타워] 대마도사의 룬 영창으로 62의 연속 비전 번개를 쏟아붓습니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"궁극기": {
		"word": "궁극기",
		"name": "궁극기 (신화/궁극의오의)",
		"category": "skill",
		"cost": 3,
		"damage": 66,
		"desc": "[3글자 신화 타워] 궁극의 활자 오의를 개방하여 66의 전 화면 정화 폭격을 가합니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"승천용": {
		"word": "승천용",
		"name": "승천용 (신화/승천하는용)",
		"category": "summon",
		"cost": 3,
		"damage": 70,
		"desc": "[3글자 신화 타워] 하늘로 승천하는 거대한 용이 70의 뇌전 폭풍을 몰고 옵니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"광전신": {
		"word": "광전신",
		"name": "광전신 (신화/전쟁의신)",
		"category": "weapon",
		"cost": 3,
		"damage": 65,
		"desc": "[3글자 신화 타워] 전쟁의 신이 강림하여 65의 무자비한 도끼 난타를 퍼붓습니다.",
		"icon": "res://assets/01_무기_공격/axe_도끼/axe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"사신포": {
		"word": "사신포",
		"name": "사신포 (신화/영혼의대포)",
		"category": "weapon",
		"cost": 3,
		"damage": 63,
		"desc": "[3글자 신화 타워] 적의 영혼을 탄환으로 쏘아올려 63의 강력한 사신 포격을 가합니다.",
		"icon": "res://assets/01_무기_공격/cannon_포/cannon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"신의빛": {
		"word": "신의빛",
		"name": "신의빛 (신화/신성한광휘)",
		"category": "heal",
		"cost": 3,
		"damage": 50,
		"desc": "[3글자 신화 타워] 신의 빛이 내리쬐어 50 광휘 피해 및 기지 HP를 넉넉하게 재생시킵니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"치유탑": {
		"word": "치유탑",
		"name": "치유탑 (신화/영구치유탑)",
		"category": "heal",
		"cost": 3,
		"damage": 44,
		"desc": "[3글자 신화 타워] 44의 치유 광탄을 쏘며 매 웨이브마다 기지 최대 체력을 증대합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"마력샘": {
		"word": "마력샘",
		"name": "마력샘 (신화/무한의마력)",
		"category": "skill",
		"cost": 3,
		"damage": 48,
		"desc": "[3글자 신화 타워] 무한히 솟아나는 마력으로 48 피해 및 전 타워 공격 쿨타임을 30% 단축합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"질주마": {
		"word": "질주마",
		"name": "질주마 (신화/천마질주)",
		"category": "summon",
		"cost": 3,
		"damage": 53,
		"desc": "[3글자 신화 타워] 날개 달린 천마가 전장을 질주하며 53 피해 및 적들을 짓밟습니다.",
		"icon": "res://assets/04_생물_소환/horse_말/horse_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"불곰포": {
		"word": "불곰포",
		"name": "불곰포 (신화/화염곰의발)",
		"category": "summon",
		"cost": 3,
		"damage": 55,
		"desc": "[3글자 신화 타워] 불타는 거대 곰의 앞발로 55의 화염 분쇄 타격을 입힙니다.",
		"icon": "res://assets/04_생물_소환/bear_곰/bear_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"독룡포": {
		"word": "독룡포",
		"name": "독룡포 (신화/맹독드래곤)",
		"category": "summon",
		"cost": 3,
		"damage": 64,
		"desc": "[3글자 신화 타워] 맹독 드래곤이 64의 부식 브레스를 뿜어 모든 적을 녹입니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"빙룡포": {
		"word": "빙룡포",
		"name": "빙룡포 (신화/빙결드래곤)",
		"category": "summon",
		"cost": 3,
		"damage": 63,
		"desc": "[3글자 신화 타워] 서리 드래곤이 63의 블리자드 브레스로 전장을 꽁꽁 얼려버립니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"뇌룡포": {
		"word": "뇌룡포",
		"name": "뇌룡포 (신화/뇌전드래곤)",
		"category": "summon",
		"cost": 3,
		"damage": 65,
		"desc": "[3글자 신화 타워] 뇌전 드래곤이 65의 푸른 번개 브레스로 전장을 감전시킵니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"성벽탑": {
		"word": "성벽탑",
		"name": "성벽탑 (신화/요새방어탑)",
		"category": "defense",
		"cost": 3,
		"damage": 52,
		"desc": "[3글자 신화 타워] 난공불락의 성벽 탑에서 52의 거대 볼트를 일제 발사합니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
	"최후벽": {
		"word": "최후벽",
		"name": "최후벽 (신화/최후의방벽)",
		"category": "defense",
		"cost": 3,
		"damage": 56,
		"desc": "[3글자 신화 타워] 적의 침공을 완벽히 차단하는 최후의 방벽으로 56 충격을 줍니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": []
	},
}

func get_word_data(word: String) -> Dictionary:
	return WORD_DATABASE.get(word, {})

func get_all_words() -> Array:
	var list = []
	for k in WORD_DATABASE.keys():
		list.append(WORD_DATABASE[k])
	return list

func get_words_by_category(cat: String) -> Array:
	var list = []
	for k in WORD_DATABASE.keys():
		var data = WORD_DATABASE[k]
		if data.get("category", "") == cat:
			list.append(data)
	return list
