# WordDatabase.gd
# 100개 단어 스펙 및 고유 특수 효과 데이터베이스
extends Node

const WORD_DATABASE = {
	"검": {
		"word": "검",
		"name": "검 (무기/참격)",
		"category": "weapon",
		"cost": 1,
		"damage": 10,
		"desc": "적에게 10의 강력한 물리 베기 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"봉": {
		"word": "봉",
		"name": "봉 (무기/주문)",
		"category": "weapon",
		"cost": 1,
		"damage": 6,
		"magicPower": 4,
		"desc": "적에게 6 피해를 입히고, 다음 마법 단어의 위력을 +4 증가시킵니다.",
		"icon": "res://assets/01_무기_공격/staff_봉/staff_1_32px.png",
		"sound": "playAttack",
		"tags": [],
	},
	"공": {
		"word": "공",
		"name": "공 (타격/충격)",
		"category": "weapon",
		"cost": 1,
		"damage": 9,
		"desc": "적을 정면 강타하여 9의 묵직한 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/fist_공/fist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"목": {
		"word": "목",
		"name": "목 (급소/암살)",
		"category": "weapon",
		"cost": 1,
		"damage": 8,
		"execute": true,
		"desc": "적의 목을 베어 8 피해를 입히며, 체력 50% 이하인 적에게는 16 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/axe_목/axe_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"골": {
		"word": "골",
		"name": "골 (타격/기절)",
		"category": "weapon",
		"cost": 1,
		"damage": 8,
		"stun": true,
		"desc": "적의 머리를 강타하여 8 피해를 입히고 1턴간 기절(스턴)시킵니다.",
		"icon": "res://assets/01_무기_공격/mace_골/mace_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"쇠": {
		"word": "쇠",
		"name": "쇠 (금속/강타)",
		"category": "basic",
		"cost": 1,
		"damage": 11,
		"stripShield": 4,
		"desc": "쇳덩이를 내리쳐 11 피해를 입히고 적 방어도를 4 깎아냅니다.",
		"icon": "res://assets/01_무기_공격/iron_쇠/iron_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"못": {
		"word": "못",
		"name": "못 (도구/출혈)",
		"category": "basic",
		"cost": 1,
		"damage": 6,
		"bleed": 3,
		"desc": "날카로운 대못을 박아 6 피해를 입히고 3턴간 출혈(매 턴 3 피해)을 부여합니다.",
		"icon": "res://assets/01_무기_공격/spike_못/spike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"날": {
		"word": "날",
		"name": "날 (칼날/절단)",
		"category": "basic",
		"cost": 1,
		"damage": 8,
		"weak": 1,
		"desc": "예리한 날로 베어 8 피해를 입히고 1턴간 취약(받는 피해 30% 증가)을 부여합니다.",
		"icon": "res://assets/01_무기_공격/blade_날/blade_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"삭": {
		"word": "삭",
		"name": "삭 (바람/삭풍)",
		"category": "basic",
		"cost": 1,
		"damage": 8,
		"breakShield": true,
		"desc": "매서운 삭풍을 휘둘러 8 피해를 입히고 적의 모든 실드를 제거합니다.",
		"icon": "res://assets/01_무기_공격/wind_slash_삭/wind_slash_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"일": {
		"word": "일",
		"name": "일 (신성/일격)",
		"category": "basic",
		"cost": 1,
		"damage": 15,
		"desc": "혼신의 일격을 날려 15의 치명적인 단일 물리 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/strike_일/strike_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"십": {
		"word": "십",
		"name": "십 (신성/십자)",
		"category": "basic",
		"cost": 1,
		"damage": 6,
		"hits": 2,
		"desc": "십자 형태로 베어 6 피해를 2회(총 12 피해) 연속 공격합니다.",
		"icon": "res://assets/01_무기_공격/cross_sword_십/cross_sword_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"박": {
		"word": "박",
		"name": "박 (신체/박치기)",
		"category": "basic",
		"cost": 1,
		"damage": 9,
		"stun": true,
		"selfDmg": 2,
		"desc": "단단한 박치기로 9 피해를 입히고 적을 1턴간 기절시킵니다. (자신 2 반동 피해)",
		"icon": "res://assets/01_무기_공격/ram_박/ram_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"발": {
		"word": "발",
		"name": "발 (사격/발포)",
		"category": "weapon",
		"cost": 1,
		"damage": 10,
		"pierce": true,
		"desc": "탄환을 발사하여 10의 원거리 물리 관통 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/shot_발/shot_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"괴": {
		"word": "괴",
		"name": "괴 (변이/폭주)",
		"category": "basic",
		"cost": 1,
		"damage": 16,
		"selfDmg": 3,
		"desc": "괴력을 발휘하여 자신의 HP 3을 소모하고 적에게 16의 폭발적 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/monster_arm_괴/monster_arm_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"시": {
		"word": "시",
		"name": "시 (암기/신속)",
		"category": "basic",
		"cost": 0,
		"damage": 5,
		"desc": "날카로운 시위를 튕겨 0 AP로 5의 신속 찌르기 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/arrow_시/arrow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"구": {
		"word": "구",
		"name": "구 (마법/구체)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"magicDebuff": 0.3,
		"desc": "마력 구체를 투척하여 8 마법 피해를 입히고 1턴간 적의 마법 저항을 30% 깎습니다.",
		"icon": "res://assets/01_무기_공격/orb_구/orb_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"상": {
		"word": "상",
		"name": "상 (상흔/추뎀)",
		"category": "basic",
		"cost": 1,
		"damage": 8,
		"statusCrit": true,
		"desc": "깊은 상흔을 내어 8 피해를 입히며, 대상이 상태이상일 경우 2배(16) 피해를 입힙니다.",
		"icon": "res://assets/01_무기_공격/wound_상/wound_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"압": {
		"word": "압",
		"name": "압 (제압/압박)",
		"category": "basic",
		"cost": 1,
		"damage": 8,
		"weaken": 3,
		"desc": "적을 강하게 억눌러 8 피해를 입히고 1턴간 적의 공격력을 3 감소시킵니다.",
		"icon": "res://assets/01_무기_공격/press_압/press_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"방": {
		"word": "방",
		"name": "방 (방어/충격파)",
		"category": "defense",
		"cost": 1,
		"damage": 12,
		"knockback": 40.0,
		"slow": 0.4,
		"desc": "접근하는 적들에게 12의 방어 충격파를 발사하여 뒤로 밀어내고(넉백) 40% 감속시킵니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"갑": {
		"word": "갑",
		"name": "갑 (철갑/가시파편)",
		"category": "defense",
		"cost": 1,
		"damage": 15,
		"shrapnel": 3,
		"desc": "가시 철갑 파편을 사방으로 발사하여 15의 날카로운 관통 물리 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"문": {
		"word": "문",
		"name": "문 (관문/철문낙하)",
		"category": "defense",
		"cost": 1,
		"damage": 14,
		"stun": 1.5,
		"desc": "적의 경로 위에 거대한 철문을 쿵 내리찍어 14 피해를 주고 1.5초간 기절(Stun)시킵니다.",
		"icon": "res://assets/02_방어_장비/gate_문/gate_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"성": {
		"word": "성",
		"name": "성 (성채/요새포)",
		"category": "defense",
		"cost": 1,
		"damage": 18,
		"range_bonus": 40.0,
		"desc": "요새의 육중한 성채 방어포를 발사하여 18의 광역 포격 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"산": {
		"word": "산",
		"name": "산 (태산/낙석)",
		"category": "defense",
		"cost": 1,
		"damage": 18,
		"knockback": 50.0,
		"desc": "태산 같은 거대한 낙석을 떨어뜨려 18의 광역 물리 피해를 입히고 적들을 크게 밀어냅니다.",
		"icon": "res://assets/02_방어_장비/mountain_산/mountain_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"막": {
		"word": "막",
		"name": "막 (결계/감속장막)",
		"category": "defense",
		"cost": 1,
		"damage": 12,
		"slow": 0.5,
		"desc": "지나가는 적에게 12의 마법 장막 충격을 가하며 이동속도를 50% 크게 감속시킵니다.",
		"icon": "res://assets/02_방어_장비/barrier_막/barrier_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"완": {
		"word": "완",
		"name": "완 (완벽/철퇴타격)",
		"category": "defense",
		"cost": 1,
		"damage": 16,
		"stun": 0.8,
		"desc": "완벽한 타이밍의 묵직한 철퇴 강타로 16 단일 물리 피해를 주고 0.8초간 기절시킵니다.",
		"icon": "res://assets/02_방어_장비/guard_완/guard_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"궁": {
		"word": "궁",
		"name": "궁 (구조/궁전)",
		"category": "basic",
		"cost": 1,
		"shield": 13,
		"retainShield": true,
		"desc": "궁전 결계를 쳐 13 방어도를 얻고 2턴 동안 방어도가 파괴되지 않습니다.",
		"icon": "res://assets/02_방어_장비/palace_궁/palace_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"인": {
		"word": "인",
		"name": "인 (인내/강철탄)",
		"category": "defense",
		"cost": 1,
		"damage": 14,
		"desc": "강철 같은 단단한 탄환을 쏘아보내어 14의 묵직한 단일 관통 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/patience_인/patience_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"보": {
		"word": "보",
		"name": "보 (구조/보루)",
		"category": "basic",
		"cost": 1,
		"shield": 14,
		"energyNext": 1,
		"desc": "최후의 보루를 세워 14 방어도를 얻고 다음 턴 AP 1을 보존합니다.",
		"icon": "res://assets/02_방어_장비/fortress_보/fortress_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"언": {
		"word": "언",
		"name": "언 (언약/신성광선)",
		"category": "defense",
		"cost": 1,
		"damage": 15,
		"desc": "신성의 언약 빛기둥을 내리꽂아 15의 신성 광역 피해를 적들에게 가합니다.",
		"icon": "res://assets/02_방어_장비/pledge_언/pledge_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"위": {
		"word": "위",
		"name": "위 (위성/궤도레이저)",
		"category": "defense",
		"cost": 1,
		"damage": 13,
		"rapid_fire": true,
		"desc": "주변을 회전하는 궤도 레이저를 연사하여 13의 지속 마법 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/orbit_위/orbit_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"누": {
		"word": "누",
		"name": "누 (구조/누각)",
		"category": "basic",
		"cost": 1,
		"shield": 10,
		"shieldNext": 5,
		"desc": "높은 누각을 세워 10 방어도를 얻고 다음 턴 시작 시 5 방어도를 추가로 얻습니다.",
		"icon": "res://assets/02_방어_장비/tower_누/tower_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"굴": {
		"word": "굴",
		"name": "굴 (자연/은신)",
		"category": "basic",
		"cost": 1,
		"shield": 8,
		"parry": 1,
		"desc": "동굴 속으로 피신하여 8 방어도를 얻고 적의 단일 공격을 1회 패링(무효화)합니다.",
		"icon": "res://assets/05_구조_필드/cave_굴/cave_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"반": {
		"word": "반",
		"name": "반 (전술/반격)",
		"category": "basic",
		"cost": 1,
		"shield": 6,
		"counter": 5,
		"desc": "6 방어도를 얻고, 이번 턴 피격받을 때마다 공격자에게 5 반격 피해를 입힙니다.",
		"icon": "res://assets/02_방어_장비/counter_shield_반/counter_shield_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"울": {
		"word": "울",
		"name": "울 (구조/울타리)",
		"category": "basic",
		"cost": 1,
		"shield": 8,
		"thorns": 4,
		"desc": "가시 울타리를 둘러 8 방어도를 얻고 가시 4(피격 시 4 반사 피해)를 얻습니다.",
		"icon": "res://assets/02_방어_장비/fence_울/fence_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"솜": {
		"word": "솜",
		"name": "솜 (완충/흡수)",
		"category": "basic",
		"cost": 1,
		"shield": 8,
		"physAbsorb": 0.5,
		"desc": "푹신한 솜 방어막으로 8 방어도를 얻고 이번 턴 물리 피해를 50% 흡수합니다.",
		"icon": "res://assets/02_방어_장비/cotton_솜/cotton_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"옷": {
		"word": "옷",
		"name": "옷 (장비/의복)",
		"category": "basic",
		"cost": 1,
		"shield": 8,
		"magicResist": 0.3,
		"desc": "마법 의복을 둘러 8 방어도를 얻고 2턴간 모든 마법 피해를 30% 경감합니다.",
		"icon": "res://assets/02_방어_장비/cloth_옷/cloth_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"불": {
		"word": "불",
		"name": "불 (원소/화염)",
		"category": "element",
		"cost": 1,
		"damage": 7,
		"burn": 4,
		"desc": "적에게 7 화염 피해를 입히고 3턴간 화상(매 턴 4 피해)을 부여합니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"물": {
		"word": "물",
		"name": "물 (원소/수류)",
		"category": "element",
		"cost": 1,
		"damage": 6,
		"shield": 6,
		"cleanse": true,
		"desc": "적에게 6 피해를 입히고, 6 방어도를 얻으며 자신의 모든 디버프를 정화합니다.",
		"icon": "res://assets/03_원소_마법/water_물/water_1_32px.png",
		"sound": "playMagic",
		"tags": [],
	},
	"빙": {
		"word": "빙",
		"name": "빙 (원소/빙결)",
		"category": "element",
		"cost": 1,
		"damage": 7,
		"freeze": 4,
		"desc": "적을 얼려 7 냉기 피해를 입히고 1턴간 적의 공격력을 4 감소시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"비": {
		"word": "비",
		"name": "비 (자연/정화)",
		"category": "basic",
		"cost": 1,
		"heal": 6,
		"extinguish": true,
		"desc": "단비가 내려 체력 6을 회복하고 전장의 모든 화상 효과를 소멸시킵니다.",
		"icon": "res://assets/03_원소_마법/rain_비/rain_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"광": {
		"word": "광",
		"name": "광 (원소/섬광)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"interrupt": true,
		"desc": "눈부신 섬광을 터뜨려 8 피해를 입히고 적의 이번 턴 공격 의도를 취소시킵니다.",
		"icon": "res://assets/03_원소_마법/flash_광/flash_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"노": {
		"word": "노",
		"name": "노 (원소/노을)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"burn": 3,
		"desc": "타오르는 노을빛으로 8 광역 피해를 입히고 2턴간 화상(매 턴 3)을 부여합니다.",
		"icon": "res://assets/03_원소_마법/ember_노/ember_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"암": {
		"word": "암",
		"name": "암 (원소/암흑)",
		"category": "element",
		"cost": 1,
		"damage": 9,
		"stealAtk": 2,
		"desc": "어둠의 파동을 뿜어 9 암흑 피해를 입히고 적 공격력을 2 영구 흡수합니다.",
		"icon": "res://assets/03_원소_마법/darkness_암/darkness_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"우": {
		"word": "우",
		"name": "우 (원소/뇌우)",
		"category": "element",
		"cost": 1,
		"damage": 11,
		"blind": 1,
		"desc": "천둥과 폭우를 소환하여 11 뇌전 피해를 입히고 1턴간 적을 실명시킵니다.",
		"icon": "res://assets/03_원소_마법/thunder_rain_우/thunder_rain_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"와": {
		"word": "와",
		"name": "와 (원소/와류)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"halveShield": true,
		"desc": "소용돌이를 일으켜 8 수류 피해를 입히고 적의 방어도를 절반으로 깎습니다.",
		"icon": "res://assets/03_원소_마법/whirlpool_water_와/whirlpool_water_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"얼": {
		"word": "얼",
		"name": "얼 (원소/빙하)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"freeze": 4,
		"desc": "빙하 파편을 꽂아 8 냉기 피해를 입히고 1턴간 적의 공격력을 4 깎습니다.",
		"icon": "res://assets/03_원소_마법/freeze_얼/freeze_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"업": {
		"word": "업",
		"name": "업 (원소/업화)",
		"category": "element",
		"cost": 1,
		"damage": 10,
		"burnReflect": 4,
		"desc": "인과의 불꽃으로 10 피해를 입히고, 적이 공격할 때마다 4 화염 반사 피해를 줍니다.",
		"icon": "res://assets/03_원소_마법/karma_ember_업/karma_ember_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"음": {
		"word": "음",
		"name": "음 (음파/충격)",
		"category": "basic",
		"cost": 1,
		"damage": 6,
		"pierce": true,
		"silence": 1,
		"desc": "강력한 진동 음파로 6 관통 피해를 입히고 적의 마법 시전을 차단합니다.",
		"icon": "res://assets/03_원소_마법/soundwave_음/soundwave_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"석": {
		"word": "석",
		"name": "석 (자연/투석)",
		"category": "basic",
		"cost": 1,
		"damage": 9,
		"breakShield": 5,
		"desc": "단단한 암석을 투척하여 9 물리 피해를 입히고 적 방어도를 5 파괴합니다.",
		"icon": "res://assets/03_원소_마법/rock_stone_석/rock_stone_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"선": {
		"word": "선",
		"name": "선 (자연/돌풍)",
		"category": "basic",
		"cost": 1,
		"damage": 7,
		"shield": 6,
		"desc": "돌풍을 소환하여 7 피해를 입히고 날아오는 적 투사체를 튕겨냅니다 (방어도 6).",
		"icon": "res://assets/03_원소_마법/wind_mist_선/wind_mist_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"섬": {
		"word": "섬",
		"name": "섬 (원소/광채)",
		"category": "element",
		"cost": 1,
		"blind100": 1,
		"desc": "극광의 섬광으로 적을 1턴간 완전 실명(공격 빗맞힘 100%) 상태로 만듭니다.",
		"icon": "res://assets/03_원소_마법/light_flash_섬/light_flash_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"수": {
		"word": "수",
		"name": "수 (원소/격류)",
		"category": "element",
		"cost": 1,
		"damage": 8,
		"shield": 6,
		"desc": "수류를 방출하여 적에게 8 피해를 입히고 아군에게 6 방어도를 부여합니다.",
		"icon": "res://assets/03_원소_마법/water_flow_수/water_flow_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"뇌": {
		"word": "뇌",
		"name": "뇌 (원소/뇌전)",
		"category": "element",
		"cost": 1,
		"damage": 14,
		"desc": "천둥 번개를 소환하여 적에게 14의 폭발적인 뇌전 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/lightning_bolt_뇌/lightning_bolt_1_32px_pastel.png",
		"sound": "playMagic",
		"tags": [],
	},
	"곰": {
		"word": "곰",
		"name": "곰 (생물/도발)",
		"category": "summon",
		"cost": 1,
		"damage": 6,
		"shield": 8,
		"taunt": true,
		"desc": "거대한 곰을 소환하여 6 피해를 입히고 8 실드 및 1턴간 도발(피해 흡수)을 겁니다.",
		"icon": "res://assets/04_생물_소환/bear_곰/bear_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"뱀": {
		"word": "뱀",
		"name": "뱀 (생물/맹독)",
		"category": "summon",
		"cost": 1,
		"damage": 4,
		"poison": 4,
		"desc": "초록 독사를 소환해 4 피해를 입히고 4의 맹독(지속 피해)을 주입합니다.",
		"icon": "res://assets/04_생물_소환/snake_뱀/snake_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"새": {
		"word": "새",
		"name": "새 (생물/순환)",
		"category": "summon",
		"cost": 1,
		"draw": 2,
		"desc": "정찰 새를 날려 즉시 자모 타일 2장을 추가 드로우합니다.",
		"icon": "res://assets/04_생물_소환/bird_새/bird_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"말": {
		"word": "말",
		"name": "말 (생물/질주)",
		"category": "summon",
		"cost": 1,
		"damage": 8,
		"extraAction": true,
		"desc": "야생마가 돌진하여 적에게 8 피해를 입히고 이번 턴 즉시 추가 1회 행동을 얻습니다.",
		"icon": "res://assets/04_생물_소환/horse_말/horse_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"소": {
		"word": "소",
		"name": "소 (생물/돌파)",
		"category": "summon",
		"cost": 1,
		"damage": 11,
		"breakShield": true,
		"desc": "황소가 들이받아 11 피해를 입히고 적의 모든 방어도를 완전히 파괴합니다.",
		"icon": "res://assets/04_생물_소환/bull_소/bull_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"개": {
		"word": "개",
		"name": "개 (생물/충견)",
		"category": "summon",
		"cost": 1,
		"damage": 5,
		"shield": 6,
		"desc": "충견을 소환하여 적에게 5 피해를 입히고 피해를 대신 흡수하는 6 실드를 얻습니다.",
		"icon": "res://assets/04_생물_소환/dog_wolf_개/dog_wolf_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"벌": {
		"word": "벌",
		"name": "벌 (생물/독침)",
		"category": "summon",
		"cost": 1,
		"damage": 2,
		"hits": 2,
		"poison": 3,
		"desc": "말벌 떼를 풀어 2 피해를 2회(총 4 피해) 입히고 맹독 3스택을 겁니다.",
		"icon": "res://assets/04_생물_소환/wasp_bee_벌/wasp_bee_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"범": {
		"word": "범",
		"name": "범 (생물/호랑이)",
		"category": "summon",
		"cost": 1,
		"damage": 13,
		"fear": 1,
		"desc": "호랑이의 포효로 적 전체에 13 피해를 입히고 1턴간 공포(피해량 -50%)를 겁니다.",
		"icon": "res://assets/04_생물_소환/tiger_범/tiger_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"매": {
		"word": "매",
		"name": "매 (생물/저격)",
		"category": "summon",
		"cost": 1,
		"damage": 9,
		"pierce": true,
		"desc": "매가 급강하하여 적의 방어도를 완전히 무시하는 9 관통 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/hawk_eagle_매/hawk_eagle_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"알": {
		"word": "알",
		"name": "알 (생물/부화)",
		"category": "summon",
		"cost": 1,
		"egg": true,
		"desc": "신비한 알을 품어 다음 턴 시작 시 강력한 무작위 야수(곰/범/독사)를 자동 소환합니다.",
		"icon": "res://assets/04_생물_소환/egg_알/egg_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"낭": {
		"word": "낭",
		"name": "낭 (생물/늑대)",
		"category": "summon",
		"cost": 1,
		"damage": 7,
		"reduceShield": 4,
		"desc": "늑대 무리를 불러 7 피해를 입히고 적의 방어도를 4 깎아냅니다.",
		"icon": "res://assets/04_생물_소환/wolf_낭/wolf_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"어": {
		"word": "어",
		"name": "어 (생물/물고기)",
		"category": "summon",
		"cost": 1,
		"shield": 7,
		"dodge": 0.4,
		"desc": "물고기처럼 유연하게 움직여 7 방어도를 얻고 다음 공격 회피율 40%를 얻습니다.",
		"icon": "res://assets/04_생물_소환/fish_어/fish_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"익": {
		"word": "익",
		"name": "익 (생물/날개)",
		"category": "summon",
		"cost": 1,
		"shield": 8,
		"drawNext": 1,
		"desc": "거대한 날개를 펼쳐 8 방어도를 얻고 다음 턴 드로우를 +1장 늘립니다.",
		"icon": "res://assets/04_생물_소환/wing_익/wing_1_32px_pastel.png",
		"sound": "playSummon",
		"tags": [],
	},
	"솔": {
		"word": "솔",
		"name": "솔 (자연/솔방울)",
		"category": "basic",
		"cost": 1,
		"damage": 10,
		"desc": "솔방울 폭탄을 던져 10의 범위 폭발 피해를 입힙니다.",
		"icon": "res://assets/04_생물_소환/pinecone_솔/pinecone_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"운": {
		"word": "운",
		"name": "운 (운명/행운)",
		"category": "basic",
		"cost": 1,
		"draw": 2,
		"shield": 5,
		"desc": "운명의 수레바퀴: 자모 카드 2장을 즉시 드로우하고 5 방어도를 얻습니다.",
		"icon": "res://assets/04_생물_소환/fortune_cloud_운/fortune_cloud_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"숨": {
		"word": "숨",
		"name": "숨 (숨결/영기방출)",
		"category": "heal",
		"cost": 1,
		"damage": 16,
		"aoe_cone": true,
		"desc": "전방 부채꼴 범위로 16의 거대한 영기 숨결을 뿜어내어 적들을 지속 피해로 태웁니다.",
		"icon": "res://assets/05_회복_치유/breath_숨/breath_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"생": {
		"word": "생",
		"name": "생 (생명/영혼흡수)",
		"category": "heal",
		"cost": 1,
		"damage": 14,
		"drain_hp": 1,
		"desc": "적에게 14의 영혼 흡수탄을 발사하며, 적 처치 시 기지 HP를 +1 회복합니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"샘": {
		"word": "샘",
		"name": "샘 (치유샘/물기둥)",
		"category": "heal",
		"cost": 1,
		"damage": 12,
		"airborne": 0.5,
		"desc": "바닥에서 솟구치는 거대한 물기둥을 분출하여 12 피해와 함께 적을 0.5초간 공중으로 띄웁니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"감": {
		"word": "감",
		"name": "감 (단감/투척)",
		"category": "heal",
		"cost": 1,
		"damage": 11,
		"slow": 0.3,
		"desc": "단단한 감 열매를 고속 투척하여 11 피해를 입히고 적을 30% 둔화시킵니다.",
		"icon": "res://assets/05_회복_치유/persimmon_감/persimmon_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"살": {
		"word": "살",
		"name": "살 (신체/재생)",
		"category": "basic",
		"cost": 1,
		"regen": 3,
		"duration": 3,
		"desc": "살점이 재생되어 3턴 동안 매 턴 종료 시 HP를 3씩 회복합니다.",
		"icon": "res://assets/06_회복_치유/flesh_heal_살/flesh_heal_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"봄": {
		"word": "봄",
		"name": "봄 (자연/생기)",
		"category": "basic",
		"cost": 1,
		"heal": 7,
		"reduceDebuff": 1,
		"desc": "따스한 봄기운으로 아군 체력 7 회복 및 모든 디버프 지속시간을 1턴 단축합니다.",
		"icon": "res://assets/06_회복_치유/spring_season_봄/spring_season_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"내": {
		"word": "내",
		"name": "내 (자연/청류)",
		"category": "basic",
		"cost": 1,
		"heal": 5,
		"cleanse": 2,
		"desc": "맑은 시냇물로 체력 5를 회복하고 해로운 효과 2개를 씻어냅니다.",
		"icon": "res://assets/06_회복_치유/stream_water_내/stream_water_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"식": {
		"word": "식",
		"name": "식 (보양/독초폭탄)",
		"category": "heal",
		"cost": 1,
		"damage": 13,
		"poison": 4,
		"desc": "폭발하는 독초 주머니를 던져 13 광역 피해를 입히고 초당 4의 중독 피해를 남깁니다.",
		"icon": "res://assets/05_회복_치유/food_식/food_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"실": {
		"word": "실",
		"name": "실 (도구/봉합)",
		"category": "basic",
		"cost": 1,
		"heal": 6,
		"stopBleed": true,
		"desc": "상처를 꿰매어 출혈을 즉시 멈추고 체력 6을 회복합니다.",
		"icon": "res://assets/06_회복_치유/thread_stitch_실/thread_stitch_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"온": {
		"word": "온",
		"name": "온 (자연/온천)",
		"category": "basic",
		"cost": 1,
		"heal": 7,
		"reduceDebuff": 1,
		"desc": "따스한 온천욕으로 체력 7을 회복하고 모든 디버프 지속시간을 1턴 감소시킵니다.",
		"icon": "res://assets/06_회복_치유/warm_glow_온/warm_glow_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"입": {
		"word": "입",
		"name": "입 (신체/흡혈)",
		"category": "basic",
		"cost": 1,
		"damage": 4,
		"vamp": 4,
		"desc": "적에게 4 피해를 입히고 입힌 피해만큼 체력을 그대로 흡수(흡혈)합니다.",
		"icon": "res://assets/06_회복_치유/mouth_blood_입/mouth_blood_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"월": {
		"word": "월",
		"name": "월 (신비/월광)",
		"category": "basic",
		"cost": 1,
		"damage": 9,
		"vamp": 4,
		"desc": "초승달 검기로 9 암흑 피해를 입히고 체력 4를 흡혈합니다.",
		"icon": "res://assets/06_회복_치유/moon_light_월/moon_light_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"맛": {
		"word": "맛",
		"name": "맛 (미식/포식)",
		"category": "basic",
		"cost": 1,
		"heal": 7,
		"buffAtk": 2,
		"desc": "맛있는 요리를 맛보아 체력 7을 회복하고 공격력 +2를 얻습니다.",
		"icon": "res://assets/06_회복_치유/food_tasty_맛/food_tasty_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"무": {
		"word": "무",
		"name": "무 (무/대포탄)",
		"category": "heal",
		"cost": 1,
		"damage": 15,
		"desc": "거대한 무 대포탄을 발사하여 착탄 지점에 15의 묵직한 폭발 물리 피해를 입힙니다.",
		"icon": "res://assets/05_회복_치유/radish_무/radish_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"마": {
		"word": "마",
		"name": "마 (산약/마비침)",
		"category": "heal",
		"cost": 1,
		"damage": 12,
		"stun": 1.0,
		"desc": "적의 급소에 마비 침을 발사하여 12 피해를 입히고 1초간 이동을 정지(마비)시킵니다.",
		"icon": "res://assets/05_회복_치유/yam_마/yam_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"묵": {
		"word": "묵",
		"name": "묵 (도토리묵/슬로우)",
		"category": "heal",
		"cost": 1,
		"damage": 10,
		"slow": 0.6,
		"desc": "끈적끈적한 도토리묵 덩어리를 뿜어내어 10 피해 및 적 이동속도를 60% 대폭 감속시킵니다.",
		"icon": "res://assets/05_회복_치유/jelly_묵/jelly_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"북": {
		"word": "북",
		"name": "북 (전쟁의북/고동)",
		"category": "skill",
		"cost": 1,
		"damage": 10,
		"speed_buff_aura": 0.4,
		"desc": "둥둥 울리는 북소리로 10 음파 피해를 주며, 주변 아군 타워 공격속도를 +40% 가속합니다.",
		"icon": "res://assets/06_버프_유틸/drum_북/drum_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"기": {
		"word": "기",
		"name": "기 (기공/관통기공파)",
		"category": "skill",
		"cost": 1,
		"damage": 20,
		"pierce": true,
		"desc": "일직선상 모든 적을 관통하는 푸른 기공파를 발사하여 20의 강력한 관통 피해를 입힙니다.",
		"icon": "res://assets/06_버프_유틸/ki_기/ki_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"속": {
		"word": "속",
		"name": "속 (속도/고속연사)",
		"category": "skill",
		"cost": 1,
		"damage": 8,
		"rapid_fire": true,
		"desc": "공격 쿨타임이 0.25초로 극도로 빨라 초당 4회 이상의 고속 활자 난사를 퍼붓습니다.",
		"icon": "res://assets/06_버프_유틸/speed_속/speed_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"능": {
		"word": "능",
		"name": "능 (능력/마력증폭)",
		"category": "skill",
		"cost": 1,
		"damage": 16,
		"vuln_amp": 0.3,
		"desc": "적에게 16 마력 광선을 쏘며 마력 표식을 남겨, 대상이 받는 모든 타워 피해를 +30% 증폭시킵니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"이": {
		"word": "이",
		"name": "이 (지혜/이치)",
		"category": "basic",
		"cost": 1,
		"doublePower": 1,
		"desc": "언어의 이치를 깨달아 다음 사용하는 단어 카드의 효과를 2배(100% 증폭)로 발동합니다.",
		"icon": "res://assets/07_버프_유틸/wisdom_gem_이/wisdom_gem_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"모": {
		"word": "모",
		"name": "모 (단조/모루)",
		"category": "basic",
		"cost": 1,
		"sharpWeapon": 4,
		"desc": "대장간 모루로 무기를 벼려 다음 3회 공격의 피해량을 +4 증가시킵니다.",
		"icon": "res://assets/07_버프_유틸/anvil_tool_모/anvil_tool_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"심": {
		"word": "심",
		"name": "심 (신체/고동)",
		"category": "basic",
		"cost": 1,
		"maxHp": 8,
		"buffAtk": 2,
		"desc": "심장을 강화하여 이번 전투 동안 최대 체력 +8 및 공격력 +2를 영구 획득합니다.",
		"icon": "res://assets/07_버프_유틸/heart_심/heart_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"남": {
		"word": "남",
		"name": "남 (자연/남풍)",
		"category": "basic",
		"cost": 1,
		"heal": 6,
		"buffAtk": 2,
		"desc": "따스한 남풍이 불어와 아군 체력 6 회복 및 공격력 +2 버프를 부여합니다.",
		"icon": "res://assets/07_버프_유틸/wind_south_남/wind_south_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"세": {
		"word": "세",
		"name": "세 (기세/압도)",
		"category": "basic",
		"cost": 1,
		"damage": 8,
		"buffNext": 4,
		"desc": "도도한 기세로 8 피해를 입히고 다음 내 카드의 공격력을 +4 증가시킵니다.",
		"icon": "res://assets/07_버프_유틸/power_surge_세/power_surge_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"순": {
		"word": "순",
		"name": "순 (자연/순항)",
		"category": "basic",
		"cost": 1,
		"drawNext": 2,
		"desc": "순풍의 돛을 올려 다음 턴 시작 시 자모 타일을 +2장 추가로 드로우합니다.",
		"icon": "res://assets/07_버프_유틸/pure_wind_순/pure_wind_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"복": {
		"word": "복",
		"name": "복 (운명/축복)",
		"category": "basic",
		"cost": 1,
		"randomBuff": 2,
		"desc": "오복의 축복을 받아 무작위 이로운 버프 2종(공격력, 방어도, 힐)을 획득합니다.",
		"icon": "res://assets/07_버프_유틸/fortune_lucky_복/fortune_lucky_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"금": {
		"word": "금",
		"name": "금 (황금/가호)",
		"category": "basic",
		"cost": 1,
		"shield": 8,
		"bonusGold": 0.2,
		"desc": "황금빛 가호로 8 방어도를 얻고 이번 전투 승리 시 골드 획득량이 +20% 증가합니다.",
		"icon": "res://assets/07_버프_유틸/gold_coin_금/gold_coin_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"망": {
		"word": "망",
		"name": "망 (포획망/속박)",
		"category": "skill",
		"cost": 1,
		"damage": 14,
		"stun": 1.2,
		"desc": "거대한 올가미 그물을 투척하여 14 피해를 입히고 적들을 1.2초간 묶어둡니다(속박).",
		"icon": "res://assets/06_버프_유틸/net_망/net_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"송": {
		"word": "송",
		"name": "송 (자연/송진)",
		"category": "basic",
		"cost": 1,
		"weaken": 5,
		"desc": "끈끈한 송진을 묻혀 적의 발을 묶고 다음 턴 적 공격력을 5 감소시킵니다.",
		"icon": "res://assets/07_버프_유틸/pine_resin_송/pine_resin_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"손": {
		"word": "손",
		"name": "손 (신체/공명)",
		"category": "basic",
		"cost": 1,
		"rerollTile": 1,
		"desc": "손끝의 공명으로 손패의 자모 타일 1장을 원하는 다른 자모로 변환합니다.",
		"icon": "res://assets/07_버프_유틸/hand_magic_손/hand_magic_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},
	"글": {
		"word": "글",
		"name": "글 (지혜/탐색)",
		"category": "basic",
		"cost": 1,
		"searchTile": 1,
		"desc": "문자의 지혜로 덱에서 원하는 자모 타일 1장을 직접 선택하여 손패로 가져옵니다.",
		"icon": "res://assets/07_버프_유틸/rune_script_글/rune_script_1_32px_pastel.png",
		"sound": "playAttack",
		"tags": [],
	},

	# === [2글자 복합 단어 타워 30종] ===
	"불꽃": {
		"word": "불꽃",
		"name": "불꽃 (원소/폭발)",
		"category": "element",
		"cost": 2,
		"damage": 24,
		"burn": 10,
		"desc": "[2글자 상위 타워] 24의 강력한 광역 화염 폭발을 일으키고 적들을 불태웁니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"얼음": {
		"word": "얼음",
		"name": "얼음 (원소/빙결)",
		"category": "element",
		"cost": 2,
		"damage": 18,
		"freeze": true,
		"desc": "[2글자 상위 타워] 18의 냉기 피해를 주고 적의 이동속도를 75% 둔화시킵니다.",
		"icon": "res://assets/03_원소_마법/ice_빙/ice_1_32px_pastel.png",
		"sound": "playFreeze"
	},
	"화살": {
		"word": "화살",
		"name": "화살 (무기/원거리)",
		"category": "weapon",
		"cost": 2,
		"damage": 22,
		"desc": "[2글자 상위 타워] 초장거리(220px)에서 22의 관통 화살을 빠르게 사격합니다.",
		"icon": "res://assets/01_무기_공격/arrow_시/arrow_1_32px_pastel.png",
		"sound": "playAttack"
	},
	"검술": {
		"word": "검술",
		"name": "검술 (무기/연타)",
		"category": "weapon",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 26의 예리한 검기로 적을 빠르게 2회 연속 베어 넘깁니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack"
	},
	"방패": {
		"word": "방패",
		"name": "방패 (방어/공속오라)",
		"category": "defense",
		"cost": 2,
		"damage": 20,
		"speed_buff_aura": 0.3,
		"desc": "[2글자 상위 타워] 20의 방어 충격파를 발사하며 주변 모든 아군 타워 공격속도를 +30% 증폭시킵니다.",
		"icon": "res://assets/02_방어_장비/shield_방/shield_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"성벽": {
		"word": "성벽",
		"name": "성벽 (방어/감속요새)",
		"category": "defense",
		"cost": 2,
		"damage": 22,
		"slow": 0.5,
		"desc": "[2글자 상위 타워] 22의 육중한 요새 방어탄을 발사하며 사거리 내 진입한 적들의 속도를 50% 영구 감속시킵니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"벼락": {
		"word": "벼락",
		"name": "벼락 (원소/감전)",
		"category": "element",
		"cost": 2,
		"damage": 30,
		"desc": "[2글자 상위 타워] 30의 강력한 뇌전을 떨어뜨려 최대 3체의 적에게 연쇄 감전 피해를 입힙니다.",
		"icon": "res://assets/03_원소_마법/lightning_뇌/lightning_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"폭풍": {
		"word": "폭풍",
		"name": "폭풍 (원소/소용돌이)",
		"category": "element",
		"cost": 2,
		"damage": 20,
		"desc": "[2글자 상위 타워] 거대한 소용돌이를 소환하여 범위 내 적들을 지속적으로 갈아냅니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"바람": {
		"word": "바람",
		"name": "바람 (원소/돌풍)",
		"category": "element",
		"cost": 2,
		"damage": 16,
		"desc": "[2글자 상위 타워] 강한 돌풍을 날려 적을 뒤로 넉백시킵니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"치유": {
		"word": "치유",
		"name": "치유 (회복/성역포격)",
		"category": "heal",
		"cost": 2,
		"damage": 20,
		"drain_hp": 1,
		"desc": "[2글자 상위 타워] 20의 성스러운 빛을 폭격하며, 매 웨이브 클리어 시 기지 HP를 +2 추가 회복합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"생명": {
		"word": "생명",
		"name": "생명 (회복/영혼흡수)",
		"category": "heal",
		"cost": 2,
		"damage": 22,
		"drain_hp": 1,
		"desc": "[2글자 상위 타워] 22의 강력한 영혼 흡수탄을 쏘아 기지 최대 체력을 +5 영구 증가시킵니다.",
		"icon": "res://assets/05_회복_치유/life_생/life_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"맹독": {
		"word": "맹독",
		"name": "맹독 (원소/부식)",
		"category": "element",
		"cost": 2,
		"damage": 16,
		"poison": 8,
		"desc": "[2글자 상위 타워] 적에게 초당 8의 치명적인 맹독 부식 피해를 부여합니다.",
		"icon": "res://assets/03_원소_마법/dark_orb_암/dark_orb_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"호랑": {
		"word": "호랑",
		"name": "호랑 (생물/맹수)",
		"category": "summon",
		"cost": 2,
		"damage": 28,
		"desc": "[2글자 상위 타워] 28의 맹수 타격으로 적의 방어도를 무시하고 물어뜯습니다.",
		"icon": "res://assets/04_생물_소환/bear_곰/bear_1_32px_pastel.png",
		"sound": "playSummon"
	},
	"마법": {
		"word": "마법",
		"name": "마법 (마법/비전)",
		"category": "element",
		"cost": 2,
		"damage": 25,
		"desc": "[2글자 상위 타워] 일직선상의 적을 모두 꿰뚫는 관통 비전 탄환을 발사합니다.",
		"icon": "res://assets/03_원소_마법/light_holy_광/light_holy_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"보물": {
		"word": "보물",
		"name": "보물 (유틸/황금포격)",
		"category": "skill",
		"cost": 2,
		"damage": 18,
		"gold_multiplier": 2,
		"desc": "[2글자 상위 타워] 18의 눈부신 황금 코인 탄환을 발사하며 적 처치 시 2배의 골드를 획득합니다.",
		"icon": "res://assets/06_버프_유틸/mana_능/mana_1_32px_pastel.png",
		"sound": "playBuff",
		"tags": []
	},
	"강철": {
		"word": "강철",
		"name": "강철 (방어/강철포)",
		"category": "defense",
		"cost": 2,
		"damage": 26,
		"desc": "[2글자 상위 타워] 26의 단단한 강철 볼트를 발사하여 일직선상의 적들을 분쇄합니다.",
		"icon": "res://assets/02_방어_장비/armor_갑/armor_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},
	"화염": {
		"word": "화염",
		"name": "화염 (원소/업화)",
		"category": "element",
		"cost": 2,
		"damage": 27,
		"burn": 12,
		"desc": "[2글자 상위 타워] 전방 부채꼴 범위에 27 피해의 지속 화염 방사를 뿜어냅니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playMagic"
	},

	# === [3글자 신화 단어 타워 12종] ===
	"호랑이": {
		"word": "호랑이",
		"name": "호랑이 (생물/신수)",
		"category": "summon",
		"cost": 3,
		"damage": 50,
		"desc": "[3글자 신화 타워] 50의 압도적인 맹수 포효로 적들을 공포에 질리게 하고 전방을 도륙합니다.",
		"icon": "res://assets/04_생물_소환/bear_곰/bear_1_32px_pastel.png",
		"sound": "playSummon"
	},
	"불벼락": {
		"word": "불벼락",
		"name": "불벼락 (원소/천벌)",
		"category": "element",
		"cost": 3,
		"damage": 60,
		"burn": 15,
		"desc": "[3글자 신화 타워] 60의 화염 낙뢰 폭격으로 화면 내 다수의 적을 일격에 궤멸시킵니다.",
		"icon": "res://assets/03_원소_마법/fire_불/fire_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"폭풍우": {
		"word": "폭풍우",
		"name": "폭풍우 (원소/재앙)",
		"category": "element",
		"cost": 3,
		"damage": 45,
		"freeze": true,
		"desc": "[3글자 신화 타워] 거대한 비바람 태풍을 일으켜 적 전체를 80% 슬로우 상태로 묶어둡니다.",
		"icon": "res://assets/03_원소_마법/wind_풍/wind_1_32px_pastel.png",
		"sound": "playMagic"
	},
	"얼음검": {
		"word": "얼음검",
		"name": "얼음검 (무기/동결)",
		"category": "weapon",
		"cost": 3,
		"damage": 42,
		"freeze": true,
		"desc": "[3글자 신화 타워] 42의 절대영도 검기로 적을 베는 즉시 2초간 완전히 얼려 멈춥니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playFreeze"
	},
	"독화살": {
		"word": "독화살",
		"name": "독화살 (무기/맹독)",
		"category": "weapon",
		"cost": 3,
		"damage": 38,
		"poison": 15,
		"desc": "[3글자 신화 타워] 38 피해와 함께 초당 15의 치사량 맹독을 주입하는 화살을 난사합니다.",
		"icon": "res://assets/01_무기_공격/arrow_시/arrow_1_32px_pastel.png",
		"sound": "playAttack"
	},
	"대검술": {
		"word": "대검술",
		"name": "대검술 (무기/오의)",
		"category": "weapon",
		"cost": 3,
		"damage": 55,
		"desc": "[3글자 신화 타워] 55의 초대형 참격 검기를 날려 경로 위의 모든 적을 일도양단합니다.",
		"icon": "res://assets/01_무기_공격/sword_검/sword_1_32px_pastel.png",
		"sound": "playAttack"
	},
	"용의숨": {
		"word": "용의숨",
		"name": "용의숨 (원소/신화)",
		"category": "element",
		"cost": 3,
		"damage": 70,
		"burn": 20,
		"desc": "[3글자 신화 타워] 70의 신화급 드래곤 브레스를 뿜어 전방의 모든 적을 잿더미로 만듭니다.",
		"icon": "res://assets/04_생물_소환/dragon_용/dragon_1_32px_pastel.png",
		"sound": "playSummon"
	},
	"생명수": {
		"word": "생명수",
		"name": "생명수 (회복/기적폭격)",
		"category": "heal",
		"cost": 3,
		"damage": 45,
		"speed_buff_aura": 0.5,
		"desc": "[3글자 신화 타워] 45의 성스러운 기적 폭격을 쏟아부으며 기지 체력 +5 회복 및 전 필드 아군 타워 공속을 +50% 버프합니다.",
		"icon": "res://assets/05_회복_치유/spring_샘/spring_1_32px_pastel.png",
		"sound": "playHeal",
		"tags": []
	},
	"철옹성": {
		"word": "철옹성",
		"name": "철옹성 (방어/요새포)",
		"category": "defense",
		"cost": 3,
		"damage": 48,
		"knockback": 60.0,
		"desc": "[3글자 신화 타워] 48의 무적 요새포 3연사를 발사하여 다가오는 모든 적들을 산산조각 내고 멀리 밀어냅니다.",
		"icon": "res://assets/02_방어_장비/castle_성/castle_1_32px_pastel.png",
		"sound": "playShield",
		"tags": []
	},

}

func get_word_data(word: String) -> Dictionary:
	if WORD_DATABASE.has(word):
		return WORD_DATABASE[word].duplicate(true)
	return {}

func get_all_words() -> Array:
	return WORD_DATABASE.values()